
var lib_sillabe = ["ba","ab","be","eb","bi","ib","bo","ob","bu","ub","ca","ac","ce","ec","ci","ic","co","oc","cu","uc","da","ad","de","ed",
"di","id","do","od","du","ud","fa","af","fe","ef","fi","if","fo","of","fu","uf","ga","ag","ge","eg","gi","ig","go","og","gu",
"ug","la","al","le","el","li","il","lo","ol","lu","ul","ma","am","me","em","mi","im","mo","om","mu","um","na","an","ne","en",
"ni","in","no","on","nu","un","pa","ap","pe","ep","pi","ip","po","op","pu","up","ra","ar","re","er","ri","ir","ro","or","ru",
"ur","sa","as","se","es","si","is","so","os","su","us","ta","at","te","et","ti","it","to","ot","tu","ut","va","av","ve","ev",
"vi","iv","vo","ov","vu","uv","za","az","ze","ez","zi","iz","zo","oz","zu","uz","bab","bac","bad","baf","bag","bal","bam","ban","bap",
"bar","bas","bat","bav","baz","beb","bec","bed","bef","beg","bel","bem","ben","bep","ber","bes","bet","bev","bez","bib",
"bic","bid","bif","big","bil","bim","bin","bip","bir","bis","bit","biv","biz","bob","boc","bod","bof","bog","bol","bom","bon","bop","bor","bos",
"bot","bov","boz","bub","buc","bud","buf","bug","bul","bum","bun","bup","bur","bus","but","buv","buz","cab","cac","cad","caf","cag","cal","cam",
"can","cap","car","cas","cat","cav","caz","ceb","cec","ced","cef","ceg","cel","cem","cen","cep","cer","ces","cet","cev","cez","cib","cic","cid",
"cif","cig","cil","cim","cin","cip","cir","cis","cit","civ","ciz","cob","coc","cod","cof","cog","col","com","con","cop","cor","cos","cot","cov",
"coz","cub","cuc","cud","cuf","cug","cul","cum","cun","cup","cur","cus","cut","cuv","cuz","dab","dac","dad","daf","dag","dal","dam","dan","dap",
"dar","das","dat","dav","daz","deb","dec","ded","def","deg","del","dem","den","dep","der","des","det","dev","dez","dib","dic","did","dif","dig",
"dil","dim","din","dip","dir","dis","dit","div","diz","dob","doc","dod","dof","dog","dol","dom","don","dop","dor","dos","dot","dov","doz","dub",
"duc","dud","duf","dug","dul","dum","dun","dup","dur","dus","dut","duv","duz","fab","fac","fad","faf","fag","fal","fam","fan","fap","far","fas",
"fat","fav","faz","feb","fec","fed","fef","feg","fel","fem","fen","fep","fer","fes","fet","fev","fez","fib","fic","fid","fif","fig","fil","fim",
"fin","fip","fir","fis","fit","fiv","fiz","fob","foc","fod","fof","fog","fol","fom","fon","fop","for","fos","fot","fov","foz","fub","fuc","fud",
"fuf","fug","ful","fum","fun","fup","fur","fus","fut","fuv","fuz","gab","gac","gad","gaf","gag","gal","gam","gan","gap","gar","gas","gat","gav",
"gaz","geb","gec","ged","gef","geg","gel","gem","gen","gep","ger","ges","get","gev","gez","gib","gic","gid","gif","gig","gil","gim","gin","gip",
"gir","gis","git","giv","giz","gob","goc","god","gof","gog","gol","gom","gon","gop","gor","gos","got","gov","goz","gub","guc","gud","guf","gug",
"gul","gum","gun","gup","gur","gus","gut","guv","guz","lab","lac","lad","laf","lag","lal","lam","lan","lap","lar","las","lat","lav","laz","leb",
"lec","led","lef","leg","lel","lem","len","lep","ler","les","let","lev","lez","lib","lic","lid","lif","lig","lil","lim","lin","lip","lir","lis",
"lit","liv","liz","lob","loc","lod","lof","log","lol","lom","lon","lop","lor","los","lot","lov","loz","lub","luc","lud","luf","lug","lul","lum",
"lun","lup","lur","lus","lut","luv","luz","mab","mac","mad","maf","mag","mal","mam","man","map","mar","mas","mat","mav","maz","meb","mec","med",
"mef","meg","mel","mem","men","mep","mer","mes","met","mev","mez","mib","mic","mid","mif","mig","mil","mim","min","mip","mir","mis","mit","miv",
"miz","mob","moc","mod","mof","mog","mol","mom","mon","mop","mor","mos","mot","mov","moz","mub","muc","mud","muf","mug","mul","mum","mun","mup",
"mur","mus","mut","muv","muz","nab","nac","nad","naf","nag","nal","nam","nan","nap","nar","nas","nat","nav","naz","neb","nec","ned","nef","neg",
"nel","nem","nen","nep","ner","nes","net","nev","nez","nib","nic","nid","nif","nig","nil","nim","nin","nip","nir","nis","nit","niv","niz","nob",
"noc","nod","nof","nog","nol","nom","non","nop","nor","nos","not","nov","noz","nub","nuc","nud","nuf","nug","nul","num","nun","nup","nur","nus",
"nut","nuv","nuz","pab","pac","pad","paf","pag","pal","pam","pan","pap","par","pas","pat","pav","paz","peb","pec","ped","pef","peg","pel","pem",
"pen","pep","per","pes","pet","pev","pez","pib","pic","pid","pif","pig","pil","pim","pin","pip","pir","pis","pit","piv","piz","pob","poc","pod",
"pof","pog","pol","pom","pon","pop","por","pos","pot","pov","poz","pub","puc","pud","puf","pug","pul","pum","pun","pup","pur","pus","put","puv",
"puz","rab","rac","rad","raf","rag","ral","ram","ran","rap","rar","ras","rat","rav","raz","reb","rec","red","ref","reg","rel","rem","ren","rep",
"rer","res","ret","rev","rez","rib","ric","rid","rif","rig","ril","rim","rin","rip","rir","ris","rit","riv","riz","rob","roc","rod","rof","rog",
"rol","rom","ron","rop","ror","ros","rot","rov","roz","rub","ruc","rud","ruf","rug","rul","rum","run","rup","rur","rus","rut","ruv","ruz","sab",
"sac","sad","saf","sag","sal","sam","san","sap","sar","sas","sat","sav","saz","seb","sec","sed","sef","seg","sel","sem","sen","sep","ser","ses",
"set","sev","sez","sib","sic","sid","sif","sig","sil","sim","sin","sip","sir","sis","sit","siv","siz","sob","soc","sod","sof","sog","sol","som",
"son","sop","sor","sos","sot","sov","soz","sub","suc","sud","suf","sug","sul","sum","sun","sup","sur","sus","sut","suv","suz","tab","tac","tad",
"taf","tag","tal","tam","tan","tap","tar","tas","tat","tav","taz","teb","tec","ted","tef","teg","tel","tem","ten","tep","ter","tes","tet","tev",
"tez","tib","tic","tid","tif","tig","til","tim","tin","tip","tir","tis","tit","tiv","tiz","tob","toc","tod","tof","tog","tol","tom","ton","top",
"tor","tos","tot","tov","toz","tub","tuc","tud","tuf","tug","tul","tum","tun","tup","tur","tus","tut","tuv","tuz","vab","vac","vad","vaf","vag",
"val","vam","van","vap","var","vas","vat","vav","vaz","veb","vec","ved","vef","veg","vel","vem","ven","vep","ver","ves","vet","vev","vez","vib",
"vic","vid","vif","vig","vil","vim","vin","vip","vir","vis","vit","viv","viz","vob","voc","vod","vof","vog","vol","vom","von","vop","vor","vos",
"vot","vov","voz","vub","vuc","vud","vuf","vug","vul","vum","vun","vup","vur","vus","vut","vuv","vuz","zab","zac","zad","zaf","zag","zal","zam",
"zan","zap","zar","zas","zat","zav","zaz","zeb","zec","zed","zef","zeg","zel","zem","zen","zep","zer","zes","zet","zev","zez","zib","zic","zid",
"zif","zig","zil","zim","zin","zip","zir","zis","zit","ziv","ziz","zob","zoc","zod","zof","zog","zol","zom","zon","zop","zor","zos","zot","zov",
"zoz","zub","zuc","zud","zuf","zug","zul","zum","zun","zup","zur","zus","zut","zuv","zuz","che","chi","ghe","ghi","qua","que","qui","sca","sce",
"schi","sci","sco","scu","sga","sghe","sghi","sgo","sgu","spa","spe","spi","spo","spu","sta","ste","sti","sto","stu","stan","sten","stin","ston","stun",
"fra","fre","fri","fro","fru","stra","stre","stri","stro","stru","spor","tra","tre","tri","tro","tru","trop","trol","trup","trip","trap","stel",
"pra","pre","pri","pro","pru","pran","pren","pron","bra","bre","bri","bro","bru"]

bisillabe = ["ca/sa","vo/ce","no/ce","da/do","fu/ne","lu/na","pa/ne","so/no","se/te","pi/no","la/to","er/ba","go/la","de/vo","ne/ve","lu/ca","lu/ce","re/mo","fo/ro","so/lo",
"be/ne","no/ce","di/to","vi/no","la/na","ro/sa","pen/na","not/te","ga/ra","fi/lo","tet/to","ca/ne","ro/ba","ri/so","mo/da","go/la",
"va/sca","me/tro","dra/go","ve/tro","stu/fa","scu/sa","sco/pa","ta/sca","pa/sta","so/sta","fe/sta","mo/sca","pi/sta","pre/te","pra/to",
"al/to","ir/to","ur/to","at/to","et/to","ur/lo","ot/to","al/ce","al/pi","er/ba","or/so","ar/co","ar/ma","ar/te","el/fo","el/mo","el/sa","ar/ca","or/to","al/ga","an/ta",
"or/bo","or/co","ar/pa","on/da","or/ma","or/ca"]

trisillabe = ["te/so/ro","sa/li/ta","po/sa/re","me/ri/to","su/bi/to","ca/li/ce","te/ne/ro","por/to/ne","can/di/do","ge/la/to","su/si/na","ma/ti/ta",
"pa/stel/lo","del/fi/no","lat/ti/na","al/be/ro","ci/pol/la","for/mag/gio","gal/li/na","fra/go/la","ca/mi/no","tam/bu/ro"]

quadrisillabe = ["pa/pe/ri/no","te/le/fo/no","se/ma/fo/ro","pre/sen/ta/re","no/mi/na/re","par/ti/va/mo","de/lu/de/re","po/mo/do/ro","pi/ra/mi/de","ca/na/ri/no","mu/ra/to/re",
"ca/la/mi/ta","pa/pa/ve/ri","mo/to/ri/no","tu/li/pa/ni","go/mi/to/lo","e/le/fan/te","ba/rat/to/li","bi/ci/clet/ta","am/bu/lan/za","ra/va/nel/lo","ter/mo/me/tro",
"tar/ta/ru/ga","gi/ra/so/le","fuo/ri/stra/da","mat/ta/rel/lo","a/ra/chi/di","te/le/fo/no","sco/iat/to/lo","a/spa/ra/gi"]

pentasillabe = ["di/chia/ra/zio/ne","e/du/ca/zio/ne","in/se/gna/men/to","u/ni/ver/si/tà","mo/bi/li/fi/cio","pa/ra/ca/du/te","te/le/fo/na/re","e/co/no/mi/a","te/le/pa/ti/a",
"ab/bot/to/na/re","im/pal/ca/tu/ra","me/di/ci/na/le","in/si/cu/rez/za","fa/vo/re/vo/le","cor/re/la/zio/ne","in/di/ca/to/re","in/te/ra/zio/ne",
"pas/sa/pa/ro/la","co/mu/ni/ca/re","di/chia/ra/zio/ne","te/le/vi/so/re","in/va/li/di/tà","e/du/ca/zio/ne","in/se/gna/men/to","u/ni/ver/si/tà","mo/bi/li/fi/cio","pa/ra/ca/du/te"]
