var alfabeto = ["A","B","C dolce","C dura","D","E","F","G dolce","G dura","I","L","M","N","O","P","Q","R","S","T","U","V","Z","Casuale"];
var alfabetointero = ["a","b","c","d","e","f","g","h","i","l","m","n","o","p","q","r","s","t","u","v","z"];
var parole = [
  [
    ["agenda","Si usa per segnare gli appuntamenti"],
    ["aspirina","Si prende se fa male la testa"],
    ["aquila","Un uccello che vola molto in alto"],
    ["argine","Serve a contenere il fiume"],
    ["agnello","Animale molto docile"],
    ["ampliare","Rendere più grande"],
    ["annuire","Fare cenno di sì con la testa"],
    ["arredare","Disporre i mobili nella stanza"],
    ["avvicinare","Il contrario di allontanare"],
    ["agire","Fare un'azione"],
    ["andare","Recarsi in un posto"],
    ["adesivo","Che si incolla"],
    ["angusto","Molto stretto"],
    ["anonimo","Che non ha nome"],
    ["ansiosa","Persona sempre preoccupata"],
    ["anziano","Non più giovane"],
    ["acceso","Il contrario di spento"],
    ["abbassare","Rendere più basso"],
    ["aeroplano","Vola nel cielo"],
    ["ammirare","Guardare con stupore"],
    ["armonica","Si suona con la bocca"],
    ["argento","Tra l'oro e il bronzo"],
    ["attivo","Il contrario di passivo"],
    ["altezza","In geometria assieme alla base"],
    ["aprile","Il quarto mese dell'anno"],
    ["annodare","Fare un nodo"],
    ["anello","Si mette al dito"],
    ["allenare","Lo fa il mister"],
    ["acerbo","Non ancora maturo"],
    ["assolto","Non condannato"],
    ["arancione","Colore dato da rosso e giallo"],
    ["accusare","Incolpare qualcuno"],
    ["abitare","Vivere in una casa"],
    ["architetto","Progetta le case"],
    ["ambizioso","Uno che vuole arrivare in alto"],
    ["alieno","Viene da un altro pianeta"],
    ["ananas","Frutto tropicale"],
    ["ancora","La getta la nave per fermarsi"],
    ["ariete","Il primo segno zodiacale"],
    ["assurdo","Incredibile, contro ogni logica"],
    ["attivo","Contrario di passivo"],
    ["autore","Colui che scrive un libro"],
    ["altalena","Un gioco del parco"],
    ["africa","Un continente molto caldo"],
    ["afosa","Un'estate molto calda e umida"],
    ["arrancare","Procedere molto lentamente e con fatica"],
    ["astuccio","Ci si mettono le penne e i colori"],
    ["arbitro","Fischia rigori e punizioni"],
    ["allarme","Si dà quando arrivano i nemici"],
    ["apertura","Il contrario della chiusura"],
    ["antico","Il contrario di moderno"]
  ],
  [
    ["bibita","Si beve quando si ha sete"],
    ["banana","Frutto giallo allungato"],
    ["brace","Ci si cuoce la carne"],
    ["borsa","Ci si mettono le chiavi e altri oggetti"],
    ["bufera","Turbine di vento con pioggia, neve o grandine"],
    ["bullone","Lo stringe il meccanico"],
    ["balena","Un grosso cetaceo"],
    ["banchetto","Un grande pranzo con molti invitati"],
    ["biliardo","Gioco con le stecche e il tavolo verde"],
    ["bollire","Lo fa l'acqua quando è molto calda"],
    ["buttare","Gettare, lanciare via"],
    ["bilancia","Un segno zodiacale... che pesa"],
    ["bisticcio","Lo fanno i bambini quando litigano"],
    ["bambino","Un ragazzo... un po' più piccolo"],
    ["branchie","Le usano i pesci per respirare"],
    ["broccolo","Una verdura a forma di piccolo albero"],
    ["bruciare","Lo fa qualcosa che prende a fuoco"],
    ["briscola","Un gioco di carte"],
    ["baciare","Un gesto d'affetto"],
    ["bucato","Lo è il calzino non integro"],
    ["battuta","Dà il via all'azione nel tennis"],
    ["biforcuta","La lingua del serpente"],
    ["binario","Vi cammina sopra il treno"],
    ["biologia","Materia che studia gli esseri viventi"],
    ["boccacce","Le fa il maleducato"],
    ["bollicine","Le fa lo champagne"],
    ["braccioli","La poltrona ne ha due"],
    ["bradipo","L'animale più lento"],
    ["briciole","Restano dopo aver mangiato"],
    ["brillante","Che luccica o risplende"],
    ["brufolo","Appare sulla pelle"],
    ["bocciato","Il contrario di promosso"],
    ["Buffone","Fa ridere la gente"],
    ["bianco","Il colore più candido"],
    ["bagaglio","Si porta dietro quando si viaggia"],
    ["bambola","Un gioco per i più piccoli"],
    ["bandiera","Quella dell'Italia ha tre colori"],
    ["basilico","Si usa per fare il pesto"],
    ["bastone","Un aiuto per camminare"],
    ["benedetto","Che ha ricevuto una benedizione"],
    ["bravissimo","Più che bravo"],
    ["breve","Il contrario di lungo"],
    ["brocca","Contiene l'acqua o il vino"],
    ["bruschetta","Pane, sale, olio e pomodoro"],
    ["busta","Vi si mette dentro la lettera"],
    ["berretto","Ripara la testa"],
    ["buono","Il contrario di cattivo"],
    ["bussare","Si fa prima di entrare"],
    ["bugiardo","Non dice la verità"],
    ["brotolone","Chi si lamenta sempre"],
    ["badare","Prendersi cura di qualcosa"]
  ],
  [
    ["cintura","Si allaccia prima di partire"],
    ["cigno","Elegante animale del lago"],
    ["circuito","Vi corrono le macchine"],
    ["ciliegia","Un frutto che... va in coppia"],
    ["cinese","Viene dalla cina"],
    ["civetta","Un uccello notturno"],
    ["cipolla","Quando si sbuccia fa piangere"],
    ["ciuffo","Capelli che... sporgono"],
    ["ciuccio","Lo tengono in bocca i bambini"],
    ["ciclico","Che si ripete periodicamente"],
    ["ciclope","Ha un solo occhio"],
    ["centimetro","Unità di misura molto piccola"],
    ["celeste","Un colore della famiglia del blu"],
    ["cerimonia","Lo è il matrimonio"],
    ["cerniera","Chiude i vestiti"],
    ["celere","Molto rapido e veloce"],
    ["centrare","Colpire il bersaglio"],
    ["cessione","Vendita di qualcosa"],
    ["cestino","Vi si mette dentro il cibo"],
    ["ciclismo","Lo sport con la bicicletta"],
    ["cilindro","Un cappello molto elegante"],
    ["cimice","Un piccolo insetto rumoroso"],
    ["cipresso","Un albero molto stretto e alto"],
    ["cinema","Ci si va a vedere i film"],
    ["civile","Non è un militare"],
    ["cereali","Lo sono il frumento e il riso"],
    ["celebre","Lo è un uomo molto famoso"],
    ["cellula","L'unità degli esseri viventi"],
    ["cinquanta","La metà di cento"],
    ["cialda","Quella del cono è croccante"],
    ["ciglia","Si trovano sugli occhi"],
    ["ciabatte","Si indossano al mare"],
    ["cenere","Resta alla fine del falò"],
    ["celare","Nascondere qualcosa a qualcuno"],
    ["cieco","Una persona che non può vedere"],
    ["cenone","Si fa la sera di capodanno"],
    ["cipria","Si passa sul viso"],
    ["civico","Il numero che identifica le abitazioni"],
    ["ciurma","L'equipaggio del pirata"],
    ["citare","Riportare il nome di un autore"],
    ["cioccolata","Dolce scuro molto amato dai bambini"],
    ["centenario","Si festeggia ogni 100 anni"],
    ["cemento","Materiale molto usato in costruzioni"],
    ["centrale","Non è laterale né periferico"],
    ["cervello","L'organo con cui pensiamo"],
    ["ciottoli","Sassi levigati che si trovano al mare"],
    ["circondare","Accerchiare qualcuno che vuole fuggire"],
    ["citofono","Contiene i nomi di chi vive in un appartamento"],
    ["ciondolo","Si porta appeso al collo"],
    ["cantante","Si esibisce davanti al microfono"],
    ["cercare","Lo fa chi spera di trovare qualcosa"]
  ],
  [
    ["calmo","Non è agitato"],
    ["camice","Lo indossa il medico"],
    ["calcare","Pressare la matita sul foglio"],
    ["calamita","Attira i metalli"],
    ["canditi","Si trovano nel panettone"],
    ["chiedere","Si fa per avere informazioni"],
    ["chiodo","Si pianta col martello"],
    ["calendario","Segna i giorni dell'anno"],
    ["contadino","Persona che lavora la terra"],
    ["calmare","Placare una persona arrabbiata"],
    ["cotoletta","Un secondo a base di carne"],
    ["clarinetto","Uno strumento a fiato"],
    ["clorofilla","Rende verdi le piante"],
    ["classico","Non passa mai di moda"],
    ["collisione","Scontro fra due auto"],
    ["collutorio","Si usa per l'igiene dentale"],
    ["capitano","Comanda la sua squadra"],
    ["coltello","A tavola insieme alla forchetta"],
    ["colomba","Dolce tipico pasquale"],
    ["combattere","Lottare contro qualcuno o qualcosa"],
    ["commovente","Che suscita dei sentimenti"],
    ["compagno","Persona con cui si va a scuola"],
    ["competente","Persona che conosce la materia"],
    ["compiuta","Una missione appena completata"],
    ["condire","Aggiungere sale e olio al cibo"],
    ["conduttore","Presenta il programma televisivo"],
    ["condannare","Dare una pena a qualcuno"],
    ["conferenza","Convegno su un argomento"],
    ["consultare","Andare a chiedere un parere"],
    ["contorto","Poco chiaro, non diritto"],
    ["convento","Vi si radunano i frati"],
    ["coraggioso","Il contrario di codardo"],
    ["cravatta","Sulla camicia negli abiti eleganti"],
    ["crocchetta","Patata fritta e impanata"],
    ["custodire","Nascondere qualcosa con cura"],
    ["crollare","Cadere a terra rovinosamente"],
    ["cordata","Gruppo di scalatori di montagna"],
    ["crostata","Dolce con cioccolata o marmellata"],
    ["criniera","Ce l'ha sulla testa il leone"],
    ["carrozza","Mezzo di trasporto trainato da cavalli"],
    ["collana","Ornamento da indossare al collo"],
    ["calore","Lo emana la candela o la stufa"],
    ["contorno","Accompagna la carne o il pesce"],
    ["consiglio","Si chiede a chi ne sa di più"],
    ["chiocciola","Animale con una casa... a spirale"],
    ["chiassoso","Una persona che fa molto rumore"],
    ["credere","Avere fiducia in qualcosa o qualcuno"],
    ["costante","Una persona stabile, perseverante"],
    ["costume","Si indossa al mare"],
    ["coprire","Mettere un telo o un vestito su qualcosa"]
  ],
  [
    ["decine","Tra le centinaia e le migliaia"],
    ["debitore","Deve dei soldi a qualcuno"],
    ["dubitare","Non essere sicuri di qualcosa"],
    ["delusa","Non soddisfatta per le sue aspettative"],
    ["dentro","Contrario di fuori"],
    ["dietro","Non è davanti"],
    ["denaro","Serve per comprare merci e servizi"],
    ["divieto","Impedisce di fare qualcosa"],
    ["doccia","Si fa per lavarsi"],
    ["dodici","L'ora del mezzogiorno"],
    ["docile","Calmo, mansueto, si fa addomesticare"],
    ["dorata","Una decorazione color oro"],
    ["doppie","Due consonanti uguali di seguito"],
    ["dottore","Cura i pazienti"],
    ["dovere","Una cosa che bisogna fare"],
    ["diritto","Una cosa che ci spetta"],
    ["duraturo","Che resiste a lungo nel tempo"],
    ["danzare","Un sinonimo di ballare"],
    ["davanti","Non è dietro"],
    ["delfino","Cetaceo molto intelligente"],
    ["dedica","La scrive l'autore all'inizio del libro"],
    ["denti","Si trovano all'interno della bocca"],
    ["deporre","La gallina quando fa un uovo"],
    ["diavolo","Contrario dell'angelo"],
    ["disdire","Annullare un ordine"],
    ["despota","Tiranno, dittatore"],
    ["disputare","Giocare una partita"],
    ["diversi","Contrario di uguali"],
    ["diluvio","Una pioggia che non finisce mai"],
    ["diventare","Cambiare in qualcosa di nuovo"],
    ["docente","Sinonimo di insegnante"],
    ["domanda","Chi la fa si aspetta una risposta"],
    ["duplice","Che riguarda due cose"],
    ["drago","Animale leggendario che sputa fuoco"],
    ["durante","Mentre avviene qualcosa"],
    ["dentista","Dottore che cura i denti"],
    ["definizione","La spiegazione di una parola"],
    ["demolire","Buttar giù un palazzo"],
    ["deridere","Prendere in giro qualcuno"],
    ["disegnare","Fare delle immagini su un foglio"],
    ["discutere","Parlare di qualcosa"],
    ["distante","Contrario di vicino"],
    ["dividere","Contrario di unire"],
    ["doppione","Ne abbiamo già uno"],
    ["domatore","Addestra gli animali selvatici"],
    ["dolcezza","La mostra chi si comporta con delicatezza"],
    ["delicato","Un sapore leggero e piacevole"],
    ["destra","All'opposto della sinistra"],
    ["dromedario","Animale con una sola gobba"],
    ["dosare","Fare delle porzioni precise"],
    ["dondolare","Andare avanti e indietro lentamente"]
  ],
  [
    ["edera","Pianta rampicante"],
    ["edile","Relativo alle costruzioni"],
    ["esile","Di corporatura minuta"],
    ["erodere","L'acqua quando scava la roccia"],
    ["evadere","Scappare da una progione"],
    ["eletto","Votato dalla popolazione"],
    ["emergere","Uscire fuori dall'acqua"],
    ["equitazione","Lo sport con i cavalli"],
    ["erbivoro","Si nutre di piante e vegetali"],
    ["esatto","Il contrario di errato"],
    ["errato","Sbagliato, non corretto"],
    ["egregio","Nelle lettere, davanti al nome"],
    ["evitare","Cercare di non fare qualcosa"],
    ["edicola","Luogo dove si vendono giornali e riviste"],
    ["eccellente","Più che ottimo"],
    ["economico","Che costa poco"],
    ["egoista","Vuole tutto per sé"],
    ["eludere","Riuscire a evitare la sorveglianza"],
    ["emotivo","Chi si fa sopraffare dalle emozioni"],
    ["empatico","Riesce a identificarsi negli altri"],
    ["entrare","Il contrario di uscire"],
    ["epoca","Un lungo periodo storico"],
    ["epica","Lo è il poema che parla dei cavalieri"],
    ["errante","Il cavaliere che va in giro senza meta"],
    ["esausto","Molto stanco e affaticato"],
    ["escluso","Messo da parte"],
    ["esigere","Richiedere qualcosa con fermezza"],
    ["esordio","La prima volta in pubblico"],
    ["estinta","Lo è una specie che non esiste più"],
    ["essere","Il verbo più usato"],
    ["esterno","Che sta fuori"],
    ["estremo","Ai limiti del possibile"],
    ["europeo","Che vive in Europa"],
    ["evasore","Colui che non paga le tasse"],
    ["elastico","Può allungarsi e accocciarsi"],
    ["elicottero","Vola in cielo, ma non è un aereo"],
    ["enorme","Molto più che grande"],
    ["epifania","La festa della befana"],
    ["eruzione","L'attività del vulcano"],
    ["esentare","Permettere a qualcuno di non fare qualcosa"],
    ["esitare","Non essere sicuri, tentennare"],
    ["esporre","Mostrare, far vedere al pubblico"],
    ["eterno","Che dura per sempre"],
    ["evolvere","Passare a uno stadio successivo"],
    ["evidenziare","Colorare un brano sul libro"],
    ["eccessivo","Veramente esagerato"],
    ["energico","Molto vigoroso, attivo"],
    ["erogare","Lo fanno le macchinette automatiche"],
    ["esercizio","Si fa per migliorare in matematica"],
    ["estendere","Allargare qualcosa a una cerchia più ampia"],
    ["espulsione","La fa l'arbitro mostrando il cartellino rosso"]
  ],
  [
    ["facile","Semplice, non difficile"],
    ["falso","Non è vero"],
    ["felice","Allegro, non triste"],
    ["festa","Si organizza per il compleanno"],
    ["flora","L'insieme delle piante"],
    ["fauna","L'insieme degli animali"],
    ["fogne","Raccolgono i rifiuti della città"],
    ["foschia","Impedisce di veder bene"],
    ["fuoco","Se lo tocchi ti bruci"],
    ["furbo","Astuto, spesso in modo poco onesto"],
    ["fabbro","Lavora i metalli"],
    ["fanale","La parte della macchina che illumina"],
    ["favore","Fare qualcosa per qualcuno in amicizia"],
    ["favola","Una storia fantastica"],
    ["felini","La famiglia del gatto e della tigre"],
    ["fiasco","Ci si mette il vino"],
    ["fiamme","Le sviluppa il fuoco quando divampa"],
    ["fidarsi","Accettare il consiglio di qualcuno"],
    ["fidanzamento","Precede il matrimonio"],
    ["fobia","Una paura ingiustificata"],
    ["foglie","Quelle degli alberi sono verdi in estate"],
    ["friggere","Passare nell'olio bollente"],
    ["frenetico","Impaziente, esagitato, irrequieto"],
    ["frutteto","Una piantagione di meli e peri"],
    ["fumare","Lo fa il camino durante l'inverno"],
    ["futuro","Al di là del presente"],
    ["formica","Un insetto piccolissimo"],
    ["fronte","Tra gli occhi e i capelli"],
    ["faccia","Comprende occhi, naso e bocca"],
    ["funghi","Appaiono sotto gli alberi dopo la pioggia"],
    ["fachiro","Dorme sul letto di chiodi"],
    ["fangoso","Un terreno pieno di melma e pozzanghere"],
    ["forbici","Si usano per tagliare"],
    ["fragile","Delicato, si rompe facilmente"],
    ["frattura","La rottura di un osso"],
    ["frigorifero","Conserva i cibi al fresco"],
    ["federa","Avvolge il cuscino"],
    ["femminile","Relativo alle donne"],
    ["ferrovia","Vi passa il treno"],
    ["fionda","Arma per lanciare i sassi"],
    ["flauto","Uno strumento a fiato"],
    ["fondere","Sciogliere un metallo"],
    ["fotografia","Si scatta e si sviluppa"],
    ["fragola","Frutto di bosco molto amato"],
    ["freddo","Contrario di caldo"],
    ["frullatore","Sminuzza e mescola i cibi"],
    ["faraone","Regnava nell'antico egitto"],
    ["fastidioso","Boioso e irritante"],
    ["forzare","Costringere a fare qualcosa"],
    ["fotocopiare","Fare un documento identico al precedente"],
    ["frenare","Arrestarsi bruscamente"]
  ],
  [
    ["gelato","Si mangia d'estate"],
    ["geranio","Una pianta che si tiene in balcone"],
    ["giacca","Si indossa quando fa freddo"],
    ["gioia","Un sentimento simile alla felicità"],
    ["giugno","Il mese in cui inizia l'estate"],
    ["giudice","Emette le sentenze"],
    ["giuria","Si esprime votando una performance"],
    ["giungere","Sinonimo di arrivare"],
    ["giunte","Le mani quando sono unite"],
    ["giunco","Pianta che cresce sulla riva del fiume"],
    ["gemelle","Nate lo stesso giorno"],
    ["gennaio","Il primo mese dell'anno"],
    ["gentile","Una persona cortese, educata"],
    ["gessetto","Si usa per scrivere alla lavagna"],
    ["gesto","Lo si fa per farsi capire"],
    ["gettare","Buttare via, lanciare"],
    ["giacere","Dormire, mettersi a letto"],
    ["ginnastica","Si fa durante l'ora di educazione fisica"],
    ["giocare","Amano farlo i bambini"],
    ["giovane","Il contrario di anziano"],
    ["giraffa","L'animale dal collo lungo"],
    ["giornale","Si legge per tenersi informati"],
    ["germoglio","Indica la nascita della pianta"],
    ["geografia","La materia degli stati, dei mari e dei monti"],
    ["gestire","Amministrare un patrimonio o una situazione"],
    ["gerundio","Il modo di chi sta compiendo l'azione"],
    ["girare","Volgere, ruotare qualcosa"],
    ["giunzione","Unisce due parti dell'ingranaggio"],
    ["geologo","Studia la composizione del terreno"],
    ["geometria","La materia dei triangoli, dei quadrati e dei cerchi"],
    ["ginocchia","Serve a piegare la gamba"],
    ["giocattolo","Lo porta Babbo Natale"],
    ["girotondo","Un gioco che si fa in cerchio"],
    ["giustizia","La chiede chi ha subito un torto"],
    ["generare","Produrre, creare qualcosa"],
    ["gerarchia","Ordine di importanza"],
    ["giacimento","Riserva di petrolio o pietre preziose"],
    ["giallo","Il romanzo con l'investigatore e l'assassino"],
    ["gigante","Un uomo veramente alto"],
    ["giavellotto","Si lancia alle olimpiadi"],
    ["giurare","Si fa per assicurare la propria sincerità"],
    ["genetica","Studia il DNA"],
    ["geroglifici","La scrittura degli antichi egizi"],
    ["giungla","Un posto pieno di alberi e animali"],
    ["giardino","All'esterno delle ville"],
    ["gioiello","Pietra preziosa di valore"],
    ["giusto","Corretto, esatto"],
    ["giocondo","Allegro, vivace"],
    ["gente","Un insieme di persone"],
    ["giostra","Si trova al Luna Park"],
    ["giullare","Buffone di corte"]
  ],
  [
    ["gatto","Un animale domestico che fa le fusa"],
    ["ghiaccio","Lo diventa l'acqua quando fa molto freddo"],
    ["gambe","Servono a camminare"],
    ["grande","Non è piccolo"],
    ["gratis","Non si paga"],
    ["grazie","Si dice dopo una cortesia"],
    ["guscio","Protegge l'uovo"],
    ["galante","Gentile, raffinato nei modi"],
    ["gallina","Depone le uova"],
    ["garza","Avvolge le ferite"],
    ["gomma","Serve per cancellare"],
    ["gorilla","Una scimmia molto grande"],
    ["gracile","Di corporatura esile, debole"],
    ["guerra","Il contrario della pace"],
    ["guancia","Tra la bocca e le orecchie"],
    ["guardare","Osservare qualcosa"],
    ["guidare","Lo si fa con la macchina"],
    ["guarire","Il contrario di ammalarsi"],
    ["gabbia","È circondata da sbarre"],
    ["galleria","Un tunnel tra le montagne"],
    ["gabbiano","Un uccello nei pressi del mare"],
    ["gasolio","Si mette in alcune macchine"],
    ["grotte","Ripari tra le montagne"],
    ["goloso","Amante del cibo"],
    ["gonfiare","Lo si fa coi palloncini"],
    ["granello","Un po' di sabbia"],
    ["grosso","Non è sottile"],
    ["grappolo","C'è quello d'uva"],
    ["grave","Un fatto negativo e importante"],
    ["grugnito","Il verso del maiale"],
    ["gustare","Assaporare con piacere"],
    ["groviera","Un formaggio a buchi"],
    ["gambero","L'animale che va indietro"],
    ["gavettone","Uno scherzo con l'acqua"],
    ["gradevole","Qualcosa di piacevole"],
    ["guarnire","Decorare un dolce"],
    ["governare","Amministrare una città o una regione"],
    ["graffiare","Fare del male con le unghie"],
    ["gongolare","Provare un'intima soddisfazione"],
    ["globuli","Quelli rossi sono nel sangue"],
    ["goccia","Cade dal lavandino quando perde"],
    ["garantire","Assicurare qualcosa"],
    ["gnomo","Piccolo essere fantastico"],
    ["gorgonzola","Un formaggio italiano"],
    ["gradire","Apprezzare qualcosa"],
    ["gradi","Si usano per misurare la temperatura"],
    ["goniometro","Strumento per misurare gli angoli"],
    ["grandioso","Eccezionale, magnifico"],
    ["grandine","Quando cade danneggia le piante"],
    ["guardiano","Tiene d'occhio una zona"],
    ["guasto","Non fa funzionare le cose"]
  ],
  [
    ["ideale","La situazione migliore"],
    ["idolo","È adorato dai fan"],
    ["idrico","Relativo all'acqua"],
    ["ignoto","Non conosciuto"],
    ["illeso","Non si è fatto male"],
    ["imbuto","Si usa per travasare l'acqua o il vino"],
    ["indice","Il secondo dito della mano"],
    ["infimo","Di bassissima qualità"],
    ["intero","Non rotto"],
    ["intesa","Quando si va d'accordo"],
    ["issare","Sollevare, portare in alto"],
    ["ittico","Relativo ai pesci"],
    ["igiene","Pulizia del corpo e dei luoghi"],
    ["imitare","Comportarsi come un altro"],
    ["imporre","Far fare qualcosa con la forza"],
    ["impronta","La lascia chi passa"],
    ["improbabile","Che difficilmente può accadere"],
    ["includere","Considerare all'interno di un gruppo"],
    ["incerto","Tutt'altro che sicuro"],
    ["indietro","Non è davanti"],
    ["indegno","Non merita qualcosa"],
    ["indurito","Lo è il pane dopo qualche giorno"],
    ["indurre","Fare in modo che qualcuno faccia una cosa"],
    ["ingenuo","Tende a fidarsi di tutti"],
    ["innocuo","Non fa del male a nessuno"],
    ["insegna","Indica il nome del locale"],
    ["insolito","Strano, non comune"],
    ["idrante","Serve a spruzzare l'acqua"],
    ["immediato","Che accade subito"],
    ["imparare","Apprendere qualcosa di nuovo"],
    ["impetuoso","Esuberante, inarrestabile"],
    ["incartare","Avvolgere un regalo"],
    ["inclinato","Non perfettamente orizzontale"],
    ["incendio","Quando le fiamme si estendono"],
    ["incisivo","Un dente che sta davanti"],
    ["indossare","Vestirsi, mettere qualcosa"],
    ["industria","Fabbrica che produce qualcosa"],
    ["infermiere","Assiste i malati"],
    ["informare","Rendere nota una notizia"],
    ["innocente","Non è colpevole"],
    ["insalata","Un piatto a base di verdure"],
    ["innovativo","Nuovo, mai visto prima"],
    ["insoluto","Che non si riesce a risolvere"],
    ["invocare","Chiamare qualcuno a gran voce"],
    ["isoscele","Un triangolo con due lati uguali"],
    ["isterico","Nervoso, esageratamente preoccupato"],
    ["immobile","Fermo, non si sposta"],
    ["illegale","Contrario alla legge"],
    ["imbarcare","Caricare sulla nave"],
    ["impaurito","Spaventato da qualcosa"],
    ["imperfetto","Fatto bene, ma con qualche difetto"]
  ],
  [
    ["ladro","Colui che ruba"],
    ["labbra","Danno i baci"],
    ["lacci","Chiudono le scarpe"],
    ["latte","Lo fa la mucca"],
    ["legare","Stringere con una corda"],
    ["limite","Quello di velocità non va superato"],
    ["limone","Un agrume giallo e aspro"],
    ["lamentarsi","Avere sempre qualcosa da ridire"],
    ["lucciola","Animale che illumina la notte"],
    ["lurido","Davvero sporco"],
    ["luglio","Uno dei mesi più caldi"],
    ["lacrime","Scendono dagli occhi"],
    ["lasagna","Un primo piatto... a strati"],
    ["leggero","Per nulla pesante"],
    ["legname","Si mette nel camino"],
    ["libreria","Vi si comprano i libri"],
    ["liquore","Una bevanda alcolica"],
    ["listino","Contiene tutti i prezzi"],
    ["lunotto","Il vetro posteriore dell'auto"],
    ["laborioso","Si dà sempre da fare"],
    ["laghetto","Piccolo specchio d'acqua"],
    ["lampante","Chiaro, evidente"],
    ["lanciere","Guerriero con un'arma lunga"],
    ["lampione","Illumina la strada"],
    ["lampadina","Si accende quando si ha un'idea"],
    ["lancetta","Si muove nell'orologio"],
    ["lavare","Pulire qualcosa con acqua"],
    ["labirinto","È difficile uscirne"],
    ["letale","Fatale, mortale"],
    ["levatoio","Il ponte dei castelli"],
    ["lattuga","Una verdura a foglia larga"],
    ["legale","Conforme alla legge"],
    ["lezione","La tiene l'insegnante"],
    ["liberare","Togliere qualcuno dalla schiavitù"],
    ["liquidi","Lo sono l'acqua, il latte e l'olio"],
    ["litigare","Non andare d'accordo, azzuffarsi"],
    ["livello","Quello del gioco deve essere superato"],
    ["loquace","Lo è chi parla molto"],
    ["luccicare","Lo l'oro quando è illuminato"],
    ["lingua","L'organo della parola"],
    ["lavandino","Per lavarsi le mani"],
    ["lento","Non è veloce"],
    ["latitudine","Fa coppia con la longitudine"],
    ["lavapiatti","Pulisce le stoviglie"],
    ["lenticchia","Un legume portafortuna"],
    ["licenziare","Mandar via dal posto di lavoro"],
    ["lucidare","Pulire per far risplendere"],
    ["laico","Non religioso"],
    ["lacuna","Una mancanza, un buco"],
    ["luna","Il nostro satellite"],
    ["lupo","Animale che ulula"]
  ],
  [
    ["mucca","Fa il latte"],
    ["madre","Madre"],
    ["mazzo","L'insieme delle carte"],
    ["mosso","Il mare con le onde"],
    ["multa","La fa il vigile"],
    ["museo","Ospita le opere d'arte"],
    ["magari","Si esclama per qualcosa che piacerebbe"],
    ["maniche","Quelle dei vestiti invernali sono lunghe"],
    ["migliaia","Dopo le centinaia"],
    ["misero","Povero, senza ricchezze"],
    ["moderno","Non è antico"],
    ["monaco","Vive nel monastero"],
    ["motore","Fa muovere la macchina"],
    ["maestro","Insegna a scuola"],
    ["malanno","Lo è il raffreddore"],
    ["marito","Ha una moglie"],
    ["mestolo","Si usa in cucina"],
    ["metallo","Lo è il ferro"],
    ["miracolo","Quando avviene l'impossibile"],
    ["mistero","Fenomeno inspiegabile"],
    ["morsetto","Serve a stringere"],
    ["mosche","Piccoli insetti che volano"],
    ["muschio","Sugli alberi e nel presepio"],
    ["musica","È piacevole da ascoltare"],
    ["mutare","Cambiare, diventare altro"],
    ["magnifico","Bellissimo, straordinario"],
    ["maldestro","Rompe sempre tutto"],
    ["malvagio","Cattivo, spietato"],
    ["mantello","Lo indossa il cavaliere"],
    ["manubrio","Fa girare la bicicletta"],
    ["mattino","Ha l'oro in bocca"],
    ["microbo","Essere vivente molto piccolo"],
    ["minuscole","Le lettere non maiuscole"],
    ["mignolo","Il dito più piccolo della mano"],
    ["mondiali","Si giocano ogni quattro anni"],
    ["molle","Non è duro né rigido"],
    ["mormorio","Parlare a bassa voce"],
    ["motosega","Attrezzo elettrico per tagliare il legno"],
    ["maiale","Animale che ruzzola nel fango"],
    ["mappamondo","Puoi trovarci tutti gli stati"],
    ["marca","La ditta che ha fatto un prodotto"],
    ["meditare","Pensare, riflettere a fondo"],
    ["mentale","Relativo al pensiero e alla mente"],
    ["meridiani","Sul mappamondo con i paralleli"],
    ["metro","Unità di misura della lunghezza"],
    ["millesimo","Più piccolo del centesimo"],
    ["militare","Relativo alle forze armate"],
    ["millennio","Più grande del secolo"],
    ["modulo","Si compila per ottenere qualcosa"],
    ["montare","Assemblare un mobile"],
    ["magico","Lo è il trucco del prestigiatore"]
  ],
  [
    ["norme","Regole da rispettare"],
    ["nuovo","Non è vecchio"],
    ["narici","Il naso ne ha due"],
    ["natura","L'insieme di piante e animali"],
    ["negare","Vietare qualcosa a qualcuno"],
    ["nevoso","Lo è il clima in alta montagna"],
    ["niente","Nulla, nessun oggetto"],
    ["nocivo","Che fa male, dannoso"],
    ["notare","Accorgersi di qualcosa"],
    ["notturno","Animale che esce di notte"],
    ["notaio","Sigla documenti molto importanti"],
    ["nostro","Mio e tuo"],
    ["nautico","Relativo al mare"],
    ["neanche","Quando non vanno bene diverse opzioni"],
    ["nervoso","Lo è un uomo sempre irritato"],
    ["nessuno","Neanche una persona"],
    ["nicchia","Incavo nel muro in cui si mette la statua"],
    ["nitrito","Il verso del cavallo"],
    ["novanta","Il numero della paura"],
    ["normale","Regolare, né buono n*cattivo"],
    ["nuziale","La marcia del matrimonio"],
    ["nacchere","Strumento musicale in legno"],
    ["natale","Si festeggia il 25 dicembre"],
    ["nebbia","Se c'è... non si vede"],
    ["nonno","Il papà del papà"],
    ["numeri","Lo sono 1, 2 e 3"],
    ["nuvoloso","Il cielo quando è coperto"],
    ["nazionale","Lo è l'Italia del calcio"],
    ["navigare","Lo fanno i marinai"],
    ["naufragio","Quando affonda la nave"],
    ["nascere","Venire al mondo"],
    ["neurologo","Il medico del cervello e dei nervi"],
    ["nostalgia","Tristezza di un luogo visitato"],
    ["nascondino","Gioco molto amato dai bambini"],
    ["nobili","Lo sono il conte, il duca e il marchese"],
    ["nutrire","Dar da mangiare"],
    ["necessario","Non se ne può fare a meno"],
    ["negozio","Luogo dove si vende la merce"],
    ["nemico","Una persona ostile, non amico"],
    ["nominare","Fare il nome di qualcuno"],
    ["notifica","Informa di un evento avvenuto"],
    ["nozze","Sinonimo di matrimonio"],
    ["negato","Contrario di accordato"],
    ["nativo","Nato e cresciuto in un posto"],
    ["naso","Tra gli occhi e la bocca"],
    ["nodo","Lo fa il marinaio"],
    ["neve","Cade quando fa freddo"],
    ["nave","Grande imbarcazione che solca i mari"],
    ["nove","L'ultimo numero a una cifra"],
    ["nudo","Non indossa alcun vestito"],
    ["nero","Il colore più scuro"]
  ],
  [
    ["obeso","Eccessivamente grasso"],
    ["oliva","Schiacciandola si ottiene l'olio"],
    ["ombra","La proietta chi sta al sole"],
    ["onore","Sentimento legato alla reputazione"],
    ["opera","La realizza l'artista"],
    ["osseo","Il tessuto del femore e del cranio"],
    ["ovile","Il recinto delle pecore"],
    ["ovale","Un cerchio un po' schiacciato"],
    ["occhiali","Si indossano per vedere meglio"],
    ["ognuno","Ciascuno, tutte le persone"],
    ["oliera","Contiene l'olio da versare"],
    ["omettere","Dimenticare di scrivere o fare qualcosa"],
    ["optare","Fare una scelta"],
    ["ortica","Una pianta che fa venire il prurito"],
    ["ospite","Si trova in casa d'altri"],
    ["ostico","Molto difficile da superare"],
    ["ostile","Non amichevole"],
    ["ostinato","Cocciuto, determinato"],
    ["ottimo","Più che buono"],
    ["ottuso","L'angolo che non è né retto né acuto"],
    ["oziare","Poltrire, far nulla"],
    ["ozono","Strato che protegge la terra"],
    ["oberare","Sovraccaricare di lavoro"],
    ["occulto","Celato, nascosto"],
    ["oceano","Più grande del mare"],
    ["offrire","Proporre qualcosa a qualcuno"],
    ["oggetto","Una cosa, uno strumento"],
    ["operaio","Lavora in fabbrica"],
    ["opaco","Non è trasparente"],
    ["organizzare","Predisporre in modo ordinato"],
    ["ordine","Sistemazione precisa"],
    ["ostello","Luogo dove dormire spendendo poco"],
    ["ottenere","Riuscire ad avere qualcosa"],
    ["ovunque","In qualunque posto"],
    ["obbligato","Costretto a fare qualcosa"],
    ["odioso","Fastidioso, che non si può apprezzare"],
    ["oculista","Il medico degli occhi"],
    ["onnivoro","Mangia qualunque cosa"],
    ["oppure","Introduce un'altra possibilità"],
    ["opporre","Mettere una cosa contro un'altra"],
    ["opuscolo","Foglio informativo"],
    ["orecchie","Servono per sentire"],
    ["ortaggi","Lo sono le carote"],
    ["oscuro","Tutt'altro che chiaro e limpido"],
    ["ovvio","Chiaro, lampante, evidente"],
    ["obliquo","Non è retto"],
    ["occupato","Il bagno quando non è libero"],
    ["offendere","Insultare, dire qualcosa di cattivo"],
    ["odore","Si percepisce attraverso il naso"],
    ["organo","Suona in chiesa"],
    ["oroscopo","Contiene i segni zodiacali"]
  ],
  [
    ["pacco","Lo consegna il postino"],
    ["parco","Puoi trovarci alberi e fontane"],
    ["porto","Vi approdano le navi"],
    ["pulce","Un piccolo animale che fa grandi salti"],
    ["punta","La fine della freccia"],
    ["ponte","Serve a superare il fiume"],
    ["prove","Si portano per sostenere una teoria"],
    ["pugno","La mano quando è chiusa"],
    ["pagine","Sono tante nel libro"],
    ["pagare","Si fa alla cassa"],
    ["palese","Chiaro, evidente a tutti"],
    ["panino","Due fette di pane e un affettato"],
    ["parata","La fa il portiere"],
    ["pareti","La stanza ne ha quattro"],
    ["pastore","Porta in giro le pecore"],
    ["penoso","Che suscita pietà"],
    ["pesare","Mettere sulla bilancia"],
    ["piante","Producono l'ossigeno che respiriamo"],
    ["pesca","Un frutto dalla buccia pelosa"],
    ["pirata","Ha la benda sull'occhio"],
    ["pomata","Si passa sul muscolo indolenzito"],
    ["posate","Si mettono a tavola"],
    ["pulito","Non è più sporco"],
    ["puzzle","È formato da tanti pezzi"],
    ["panchina","Vi siedono i calciatori non in campo"],
    ["passivo","Non è attivo"],
    ["peggiore","Contrario di migliore"],
    ["pauroso","Fifone, timido, tutt'altro che coraggioso"],
    ["pericolo","Qualcosa a cui bisogna stare attenti"],
    ["pescatore","Va in barca e tira le reti"],
    ["pianura","Non è né montagna né collina"],
    ["piccione","Un uccello di città"],
    ["pizza","La più famosa è la margherita"],
    ["polvere","Si accumula sui mobili"],
    ["panorama","Si vede quando si sale in alto"],
    ["permaloso","Si offende per qualunque cosa"],
    ["perpetuo","Costante, incessabile"],
    ["pieno","Tutt'altro che vuoto"],
    ["pilastro","Sostiene l'edificio"],
    ["pittore","Realizza i quadri"],
    ["polipo","Vive in mare e ha molti tentacoli"],
    ["poesia","Composizione in rima"],
    ["polpetta","Palla di carne macinata"],
    ["pompiere","Spegne l'incendio"],
    ["possedere","Avere, essere proprietario di qualcosa"],
    ["pranzo","Il secondo pasto della giornata"],
    ["premessa","Viene prima del discorso vero e proprio"],
    ["primo","Nella fila sta davanti a tutti"],
    ["proporre","Sottoporre un'idea a qualcuno"],
    ["privato","Il contrario di pubblico"],
    ["pungere","Lo fa la zanzara o l'ape"]
  ],
  [
    ["quasi","Non del tutto"],
    ["quale","Si chiede quando ci sono più possibilità"],
    ["quota","Quella della montagna è spesso alta"],
    ["quarzo","La pietra degli orologi di precisione"],
    ["quarto","Fra il terzo e il quinto"],
    ["quando","Si chiede per sapere una data o un orario"],
    ["quiete","La calma, la tranquillità"],
    ["quadro","È circondato dalla cornice"],
    ["quesito","Sinonimo di domanda"],
    ["quanto","Si chiede quando si vuole sapere il prezzo"],
    ["qualcuno","Non tutti, ma neanche nessuno"],
    ["quaderno","Vi si scrivono i compiti"],
    ["qualcosa","Un oggetto non meglio definito"],
    ["quindici","I minuti nel quarto d'ora"],
    ["qualsiasi","Quando va bene tutto"],
    ["questione","Un problema da sottoporre"],
    ["quadrato","Ha quattro lati uguali"],
    ["quarantena","Periodo di isolamento per malattia"],
    ["quadrifoglia","Piccola pianta portafortuna"],
    ["quotidiano","Giornale che esce tutti i giorni"],
    ["questionario","Foglio pieno di domande"],
    ["qualificarsi","Nello sport, passare al turno successivo"],
    ["quintale","Meno della tonnellata"],
    ["quiz","Un gioco con domande e risposte"]
  ],
  [
    ["radar","Individua gli aerei o le navi nascoste"],
    ["reale","Fisico, non virtuale"],
    ["razzo","Porta il missile in alto"],
    ["rotto","Non più integro"],
    ["rubare","Sottrarre qualcosa illegalmente"],
    ["rasato","Ha tagliato i capelli a zero"],
    ["remoto","Non vicino, distante"],
    ["renne","Tirano la slitta di Babbo Natale"],
    ["recinto","Serve a contenere gli animali"],
    ["radiare","Mandar via qualcuno da un gruppo"],
    ["ragno","Animale con otto zampe"],
    ["ruggito","Il verso del leone"],
    ["rettile","Lo è la lucertola"],
    ["ricco","Tutt'altro che povero"],
    ["ricurvo","Non proprio retto"],
    ["ridere","Lo si fa dopo una barzelletta"],
    ["ridurre","Diminuire le dosi o le quantità"],
    ["rinunciare","Abbandonare un'idea o un progetto"],
    ["rissoso","Vuol sempre fare a botte"],
    ["rovente","Molto caldo, bollente"],
    ["raccogliere","Prendere qualcosa da terra"],
    ["radici","Tengono l'albero saldo al terreno"],
    ["raggiante","Splendente, di ottimo umore"],
    ["ragliare","Lo fa l'asino"],
    ["randagio","Lo è il cane che vive per strada"],
    ["razziare","Rubare con un'incursione, depredare"],
    ["recidere","Tagliare il gambo di un fiore"],
    ["regalare","Dare qualcosa senza nulla in cambio"],
    ["remare","Lo si fa sulla barca che non ha vela né motore"],
    ["risposta","La aspetta chi fa una domanda"],
    ["reputare","Ritenere, avere un'idea di qualcuno"],
    ["righello","Serve a tracciare linee rette"],
    ["ritratto","Dipinto che raffigura il volto"],
    ["riunione","Incontro di persone per discutere un tema"],
    ["ritirata","La compie l'esercito sconfitto"],
    ["romantico","Che dà molta importanza ai sentimenti"],
    ["romanzo","Lunga composizione suddivisa in capitoli"],
    ["rossetto","Si passa sulle labbra"],
    ["ruvido","Non è liscio"],
    ["raggirare","Truffare, imbrogliare"],
    ["raggiungere","Arrivare a un obiettivo"],
    ["redimersi","Pentirsi, diventare onesti"],
    ["rimuovere","Togliere, sottrarre qualcosa"],
    ["rosso","Il colore che non piace al toro"],
    ["ringhiera","Aiuta a salire le scale"],
    ["ripasso","Si fa per memorizzare la lezione"],
    ["riservato","Lo è il tavolo prenotato da qualcuno"],
    ["risultato","Si ha alla fine della partita"],
    ["riverire","Adorare qualcuno in modo vistoso"],
    ["rivestire","Coprire qualcosa con un altro materiale"],
    ["ruzzolare","Cadere rovinosamente"]
  ],
  [
    ["salire","Andare in alto"],
    ["salato","Non è affatto dolce"],
    ["sabato","Precede la domenica"],
    ["salone","Grande stanza per accogliere gli ospiti"],
    ["sagoma","Il contorno di una persona"],
    ["scarpe","Si portano ai piedi"],
    ["sciatore","Scende dalla montagna con gli sci"],
    ["scuola","Ci si va per imparare"],
    ["sfarzo","Un lusso molto ostentato"],
    ["sirena","Essere metà donna e metà pesce"],
    ["sleale","Scorretto, non mantiene la parola"],
    ["solare","Allegro, di ottimo umore"],
    ["spada","La usa il cavaliere con lo scudo"],
    ["spegnere","Il contrario di accendere"],
    ["sporgersi","Affacciarsi dalla finestra"],
    ["spine","Le hanno le rose"],
    ["stadio","Vi gioca la squadra di calcio"],
    ["stalla","Dove dormono le mucche"],
    ["stesso","Uguale, davvero identico"],
    ["storia","La materia con le date e gli eventi"],
    ["strada","Bisogna seguirla per tornare a casa"],
    ["seguire","Fare lo stesso percorso di qualcuno"],
    ["storto","Non è proprio dritto"],
    ["salmone","Risale la corrente del fiume"],
    ["sazio","Ha mangiato in abbondanza"],
    ["scavare","Azione che si compie con la pala"],
    ["scalini","Formano le scale"],
    ["scimmia","Animale che vive sugli alberi"],
    ["sognare","Lo si fa quando si va a letto"],
    ["scoglio","Su quelli di mare si trovano i granchi"],
    ["scrigno","Contiene il tesoro"],
    ["scuro","Non è chiaro"],
    ["sedersi","Il contrario di alzarsi"],
    ["seminare","Lo fa il contadino sul terreno"],
    ["sentire","Avvertire qualcosa con le orecchie"],
    ["sillabe","Compongono le parole"],
    ["simile","Quasi uguale ma non proprio identico"],
    ["senape","Un condimento come il ketchup e la maionese"],
    ["socievole","Ama stare in mezzo alla gente"],
    ["somma","L'operazione che si fa col segno +"],
    ["sottrazione","L'operazione che si fa col segno -"],
    ["soprano","Una cantante dalla voce molto acuta"],
    ["sorbetto","Si beve a fine pasto per rinfrescarsi"],
    ["sottile","Tutt'altro che spesso"],
    ["speciale","Particolare, come pochi o nessuno"],
    ["spiegare","Lo fa il professore per far capire"],
    ["stanca","Lo è una persona alla fine della giornata"],
    ["stivali","Si portano ai piedi in campagna per non bagnarsi"],
    ["sudicio","Veramente sporco, lercio"],
    ["sarta","Cuce e ripara i vestiti"],
    ["sandali","Scarpe aperte tipicamente estive"]
  ],
  [
    ["tango","Un ballo tipico del sud America"],
    ["tasse","Bisogna pagarle ogni anno"],
    ["tasche","Per tenere le chiavi e il portafogli"],
    ["tanto","Il contrario di poco"],
    ["tazza","Ci si versa il latte"],
    ["tondo","Non ha spigoli"],
    ["torre","Un pezzo degli scacchi"],
    ["trono","Vi si siede il re"],
    ["tavolo","Ha quattro piedi e si trova nella stanza"],
    ["tovaglia","Si mette sul tavolo"],
    ["tenero","Non è affatto duro"],
    ["tennis","Lo sport con le racchette"],
    ["tesoro","Lo nasconde il pirata"],
    ["tisana","Si beve per rilassarsi o depurarsi"],
    ["tombino","Si trova a terra per strada"],
    ["tosse","Ce l'ha chi non sta bene"],
    ["triplo","Tre volte tanto"],
    ["troppo","Veramente tanto, esagerato"],
    ["tuorlo","Una parte dell'uovo"],
    ["tabelline","Moltiplicazioni da sapere a memoria"],
    ["tacere","Zittirsi, non dire qualcosa"],
    ["tacco","Rende la scarpa più alta"],
    ["tappeto","Quello magico è volante"],
    ["tappare","Chiudere una bottiglia"],
    ["targa","Identifica l'automobile"],
    ["terrore","Paura molto grande"],
    ["tonno","Un pesce molto grande"],
    ["tornare","Il contrario di andare"],
    ["traguardo","Alla fine della corsa"],
    ["tosatura","Si fa alla pecora per avere la lana"],
    ["tuttora","Ancora adesso"],
    ["tabaccaio","Vende francobolli e lettere"],
    ["talento","Particolare abilità per qualcosa"],
    ["tatto","Uno dei cinque sensi"],
    ["tetto","Copre la casa, può avere le tegole"],
    ["temporale","Cattivo tempo con lampi e tuoni"],
    ["tenda","Non fa entrare la luce dalla finestra"],
    ["tossico","Non fa bene alla salute"],
    ["tradurre","Rendere il libro in un'altra lingua"],
    ["tirare","Il contrario di spingere"],
    ["trasmettere","Far arrivare qualcosa a qualcuno"],
    ["televisione","Trasmette film e documentari"],
    ["tribunale","Vi lavorano i giudici e gli avvocati"],
    ["triangolo","Figura geometrica con tre lati"],
    ["tagliare","Dividere un foglio con le forbici"],
    ["termometro","Misura la febbre"],
    ["tranello","Inganno teso da qualcuno"],
    ["traffico","Se si incontra per strada si arriva tardi"],
    ["traslocare","Cambiare casa"],
    ["trapano","Serve a fare i buchi nel muro"],
    ["trasparente","Vi si vede attraverso"]
  ],
  [
    ["udire","Sinonimo di sentire, ascoltare"],
    ["umani","Lo sono gli uomini e le donne"],
    ["ulivo","L'albero che produce le olive"],
    ["umore","Può essere ottimo o pessimo"],
    ["unico","Non ce ne sono altri"],
    ["unire","Mettere insieme più pezzi"],
    ["usare","Utilizzare per uno scopo"],
    ["usato","Non è più nuovo"],
    ["urlare","Gridare a squarciagola"],
    ["uguale","Proprio identico"],
    ["ultimo","Arriva dopo tutti gli altri"],
    ["umile","Tutt'altro che arrogante"],
    ["unto","Qualcosa su cui è stato passato l'olio"],
    ["urbano","Relativo alla città"],
    ["urtare","Spingere qualcuno"],
    ["urgente","Va fatto subito"],
    ["usanza","Abitudine, tradizione"],
    ["utente","Chi usufruisce di un servizio"],
    ["udienza","La concede il sovrano"],
    ["ululato","Il verso del lupo"],
    ["uscire","Il contrario di entrare"],
    ["utile","Serve a qualcosa"],
    ["usurato","Usato troppe volte, rovinato"],
    ["ustione","Una bruciatura grave"],
    ["ubbidire","Fare il volere di qualcuno"],
    ["unghia","Alla fine del dito"],
    ["uncino","Ce l'ha il pirata nemico di Peter Pan"],
    ["uccello","Vola alto nel cielo"],
    ["ufficiale","Un grado dell'esercito"],
    ["ubriaco","Ha bevuto troppo"]
  ],
  [
    ["vento","Può soffiare molto forte"],
    ["vasca","Ci si può fare il bagno"],
    ["vespa","Insetto che vola e punge"],
    ["venire","Contrario di andare"],
    ["vedere","Azione che si fa con gli occhi"],
    ["viale","Grande strada alberata"],
    ["viola","Il colore dato da rosso e blu"],
    ["viventi","Lo sono animali e pianti"],
    ["vacanza","Si fa per staccare dal lavoro"],
    ["vagare","Andare in giro senza una meta"],
    ["vegetale","Né animale né minerale"],
    ["veleno","Non si deve assolutamente ingerire"],
    ["vene","Portano il sangue assieme alle arterie"],
    ["vinili","I vecchi dischi di una volta"],
    ["virata","L'azione della nave quando gira"],
    ["vetro","Materiale trasparente"],
    ["vangare","Lavorare il terreno"],
    ["volare","Possono farlo gli uccelli"],
    ["volere","Aspirare a qualcosa"],
    ["vostro","Tuo e suo"],
    ["vorace","Ha una fame insaziabile"],
    ["votare","Si fa alle elezioni"],
    ["valvola","Si apre per far entrare o uscire l'aria"],
    ["verdura","Mangiarla fa molto bene"],
    ["vincere","Il contrario di perdere"],
    ["vittima","Ha subìto un torto"],
    ["volpe","Animale molto furbo"],
    ["vulcano","Montagna che erutta lava"],
    ["valico","Passaggio tra due montagne"],
    ["vascello","Antica nave molto grande"],
    ["vecchio","Non più giovane"],
    ["vegliare","Stare in piedi per tenere d'occhio qualcosa"],
    ["verbale","Lo scrive il vigile"],
    ["vicino","Non è lontano"],
    ["vigoroso","Forte, di ottima costituzione"],
    ["vignetta","Piccolo disegno spesso divertente"],
    ["vuoto","Non è pieno"]
  ],
  [
    ["zecca","Animale che infastidisce i cani"],
    ["zaino","Vi si mettono i libri e i quaderni"],
    ["zanna","I denti dell'elefante"],
    ["zeppo","Pieno fino all'orlo"],
    ["zoppo","Non può camminare bene"],
    ["zolla","Pezzo di terra"],
    ["zucchero","Rende dolci i cibi"],
    ["zaffiro","Pietra preziosa spesso blu"],
    ["zattera","Imbarcazione costruita con i tronchi"],
    ["zerbino","Il tappeto davanti casa"],
    ["zebra","Animale a strisce bianche e nere"],
    ["zoccoli","Ai piedi del cavallo"],
    ["zodiaco","È composto da dodici segni"],
    ["zoologo","Studia gli animali"],
    ["zittire","Far tacere qualcuno"],
    ["zabaione","Dolce molto energetico"],
    ["zappare","Lo fa il contadino"],
    ["zavorra","Il peso della mongolfiera"],
    ["zafferano","Rende giallo il riso"],
    ["zufolo","Strumento a fiato"],
    ["zelo","Particolare cura nello svolgere qualcosa"],
    ["zero","Il numero a cui non corrisponde una quantità"],
    ["zampa","Il piede dell'animale"],
    ["zolfo","Minerale giallo infiammabile"]
  ]
]
