SETTINGTITLE = "Impostazioni";
TXT_PLAYERS = "Giocatori";
TXT_QUANTISTIMOLI = "Stimoli";
TXT_ALTERNANZA = "Alternanza turni";
TXT_CATEGORIASTIMOLI = "Categoria";
TXT_TIPOSTIMOLI = "Immagini/Parole";
TIPOSTIMOLI_ARRAY = ["Immagini","Immagine/Parola","Parole"];
CATEGORIA_ARRAY = ["Animali","Cibi","Mestieri","Mezzi di trasporto","Lettere"];
ALTERNANZA_ARRAY = ["Chi vince va avanti","Turni alternati"];
AVANTI = "AVANTI";
TORNAALMENU = "TORNA AL MENU"
TEAMS_TITLE = "Inserisci i nomi dei giocatori";
SQUADRAUNOINITIAL = "Rossi";
SQUADRADUEINITIAL = "Blu";
SQUADRATREINITIAL = "Verdi";
SQUADRAQUATTROINITIAL = "Neri";
INSERISCINOMI = "Inserisci i nomi di tutte le squadre";
CREDITS = "Sviluppato da Antonio Milanese - info@trainingcognitivo.it"
PAREGGIO = "Pareggio!";
VITTORIAPER = "Vittoria per ";
PLAYAGAIN = "Gioca ancora!"
AND = "e";
TITLE = "Memory!"
TIPOSTIMOLI_LETTERE_ARRAY = ["Maiuscole","Maiuscole/Minuscole","Minuscole"]
