var L = [
[
//Sillabe
["Sillabe CV BI-ZA","sillabe","CV","bi,ca,co,ci,da,de,di,do,fi,la,le,li,lo,ma,me,mi,mo,na,ne,ni,no,pa,po,ra,re,ri,ro,sa,se,si,so,su,ta,te,ti,to,va,ve,vi,vo,za"],
["Sillabe CV BA-ZU","sillabe","CV","ba,be,bo,bu,cu,ce,du,fa,fe,fo,fu,ga,ge,gi,go,gu,lu,mu,nu,pe,pi,pu,ru,tu,vu,ze,zi,zo,zu"],
["Sillabe CVC BAL-CAL","sillabe","CVC","bal,bam,ban,bar,bas,bat,bel,ben,ber,bil,boc,bol,bom,bon,bor,bot,but,cac,cal"],
["Sillabe CVC CAL-CON","sillabe","CVC","cam,can,cap,car,cas,cat,cel,cem,cen,cer,ces,cet,cil,cin,cir,cit,col,com,con"],
["Sillabe CVC COP-DIS","sillabe","CVC","cop,cor,cot,cut,cun,cur,dal,dan,dar,dat,dav,del,den,der,des,det,dif,dir,dis"],
["Sillabe CVC DIT-FEB","sillabe","CVC","dit,dol,don,dop,dor,dos,dot,dub,dul,dun,dur,dut,fab,fac,fal,fan,far,fat,feb"],
["Sillabe CVC FEM-GAS","sillabe","CVC","fem,fen,fer,fes,fet,fil,fin,fir,fis,fit,fol,fon,for,fos,fun,gal,gam,gan,gar,gas"],
["Sillabe CVC GAZ-LIN","sillabe","CVC","gaz,gen,ger,get,git,gon,lag,lam,lan,lar,las,lat,laz,leg,len,ler,les,let,lez,lin"],
["Sillabe CVC LIS-MEM","sillabe","CVC","lis,liz,lom,lon,lor,lot,lun,lup,mac,mag,mal,mam,man,mar,mas,mat,mec,mem"],
["Sillabe CVC MEN-NAG","sillabe","CVC","men,mer,mes,met,mez,mil,min,mis,miz,mol,mon,mor,mos,mul,mun,nac,nag"],
["Sillabe CVC NAL-PAL","sillabe","CVC","nal,nan,nar,neg,nel,nem,nen,nep,ner,nes,net,NIS,NIZ,NOL,NON,NOR,NOT,nul,nun,pac,pal"],
["Sillabe CVC PAN-PUR","sillabe","CVC","pan,par,pas,pat,peg,pel,pen,per,pet,pez,pic,pin,pit,pog,pol,pon,por,pos,pub,pul,pun,pur"],
["Sillabe CVC RAC-RIS","sillabe","CVC","rac,raf,rag,ral,ran,rap,rar,ras,rat,raz,reb,rec,red,reg,rel,ren,res,ret,rez,ric,rig,rim,rin,ris"],
["Sillabe CVC PAN-PUR","sillabe","CVC","rit,riz,roc,rom,ros,rot,rur,rus,sac,sag,sal,san,sap,sar,sas,sat,sec,seg,sel,sem,sen,ser,ses"],
["Sillabe CVC RIT-SES","sillabe","CVC","set,sic,sid,sim,sin,sis,sod,sof,sog,sol,som,son,sop,sor,sot,sub,suc,sud,suf,sug,sul,sun,sup"],
["Sillabe CVC SUR-TOL","sillabe","CVC","sur,tac,tag,tal,tan,tap,tar,tas,tat,tec,teg,tel,tem,ten,ter,tes,tet,tez,tin,tir,tis,tiz,toc,tol"],
["Sillabe CVC TON-ZAR","sillabe","CVC","ton,tor,tos,tun,tur,tut,val,van,var,vec,vel,vem,ven,ver,ves,vet,vil,vin,vir,vis,vit,vol,vor,vul,zan,zar"],
["Sillabe VCV ABA-UBU","sillabe","VCV","aba,abe,abi,abo,abu,eba,ebe,ebi,ebo,ebu,oba,obe,obi,obo,obu,iba,ibe,ibi,ibo,ibu,uba,ube,ubi,ubo,ubu"],
["Sillabe DIS A-E 1","sillabe","CV","ba,ca,da,fa,va,ta,ra,me,ma,be,de,fe,ve,te,re,ze,za,se,sa,pe,pa,ga,ge"],
["Sillabe DIS A-E 2","sillabe","CV","ab,eb,ad,ed,er,ar,en,an,al,el,em,am,az,ez,as,es,af,ef,ac,ec,ag,eg"],
["Sillabe DIS A-E","sillabe","CVC","aba,abe,eba,ebe,ara,are,era,ere,ama,ame,ema,eme,asa,ase,esa,ese,ava,ave,eva,eve"],
["Sillabe DIS B-D","sillabe","CVC","ab,ad,da,ba,bad,dab,ed,eb,bed,deb,ib,id,di,bi,ob,od,dob,bod,ub,ud,bud,dub"],
["Sillabe DIS F-V","sillabe","CVC","fa,va,fe,ve,vaf,fav,vef,fev,fi,vi,fo,vo,ov,of,fov,vof,uv,uf,fu,vu,vuv,fuv,fuf,vuf"],
["Sillabe DIS B-P","sillabe","CVC","ba,bap,pab,be,peb,pab,bep,peb,pe,pi,bi,bip,pib,po,bo,pob,bop,pu,bu,bup,pub"],
["Sillabe DIS C-G","sillabe","CVC","ca,che,ghe,ga,ag,ac,ec,che,ghe,ghi,chi,gi,ci,gu,cu,ug,uc,og,oc,co,go,cio,gio,cia,gia,ce,ge"],
["Sillabe DIS C-CH","sillabe","CVC","ca,che,chi,co,cu,cia,ce,ci,cio,ciu"],
["Sillabe DIS G-GH","sillabe","CVC","ga,ghe,ghi,go,gu,gia,ge,gi,gio,giu"],
["Sillabe DIS SC-SCH","sillabe","CVC","scia,sce,sci,scio,sciu,sca,sche,schi,sco,scu"]

],
[
//Bisillabe
["Bisillabe CV 1","parole","semplici","casa,voce,noce,dado,fune,luna,pane,sono,sete,pino,lato,erba,gola,devo,neve,luca,luce,remo,foro,solo"],
["Bisillabe CV 2","parole","semplici","duna,pila,vela,mela,teso,reso,leso,cosa,pipa,lana,rito,vino,riso,gufo,vano,raso,gino,fifa,muro,bene"],
["Bisillabe CV 3","parole","semplici","cono,molo,pari,pomo,lago,luce,luna,lupo,mano,modo,nave,neve,nome,pace,sera,sole,topo,uomo,vita,voce"],
["Bisillabe CV e VC 1","parole","semplici","alga,arco,arma,asta,atto,base,bene,cima,dado,dama,dito,faro,gelo,gola,idea,moda,nano,nero,nido,noce,nota,onda,orto,oste"],
["Bisillabe CV e VC 2","parole","semplici","oste,palo,pena,pepe,pino,polo,remo,riga,alto,riva,roba,sale,seta,sete,tela,tono,toro,ente,tuta,vaso,vela,vino,volo"],
["Bisillabe CV e VC 1","nonparole","semplici","tose,lopa,nape,eppe,nopi,lopo,rome,gari,sori,ravi,rabo,lase,tase,este,late,onto,roto,buto,tatu,sova,lave,novi,lovo"],
["Bisillabe CV e VC 2","nonparole","semplici","agla,cora,rama,tasa,otta,seba,nebe,maci,doda,mada,todi,rofa,loge,loga,edia,damo,onna,rone,ondi,neco,tano,ando,otro,esto"],
["Bisillabe CV e VC 3","nonparole","semplici","noco,lomo,rapi,eadi,galo,celu,nula,pulo,noma,domo,neva,enve,mone,cepa,ersa,olse,poto,oumo,tavi,cevo"],
["Bisillabe CV e VC 4","nonparole","semplici","nadu,lapi,lave,elma,sote,sore,selo,saco,ippa,nala,roti,nivo,sori,fogu,navo,sora,nogi,fafi,rumo,nebe"],
["Bisillabe CV e VC 5","nonparole","semplici","saca,cevo,ceno,doda,nefu,nalu,nepa,noso,este,nopi,tola,rabe,loga,vode,enve,calu,mero,rofo,loso"],
["Bisillabe con doppie","parole","doppie","atto,otto,etto,asso,ossa,esso,anno,anni,ebbe,ecco,elle,emme,enne,erre,esse,unno"],
["Bisillabe DIS doppie","parole","discriminazione","ele,elle,aso,asso,osa,ossa,issa,isa,tono,tonno,roso,rosso,fato,fatto,eto,etto,poso,posso,uno,unno,molo,mollo"],
["Bisillabe DIS C-CH","parole","discriminazione","cina,china,cena,cento,chiesa,chiave,cesto,cono,ciuffo,cuffia,caldo,cialda,caro,certo,chela,voce,poche,luce,luca,lucia"],
["Bisillabe DIS G-GH","parole","discriminazione","ago,agio,ghiro,giro,gonna,giorno,gallo,giallo,gita,ghisa,gesto,magi,maghi,pregi,preghi,oggi,logo"],
["Bisillabe DIS SC-SCH","parole","discriminazione","ascia,nasce,esche,esce,esca,tasche,pesca,pesce,pesci,peschi,lisca,liscia,lische,fresche,cosce"],
["Bisillabe DIS accenti","parole","discriminazione","porto,portò,faro,farò,giro,girò,presto,prestò,città,avrò,pesto,pestò,gesto,sara,sarò,fata,farò"]

],
[
//Trisillabe
["Trisillabe CV 1","parole","semplici","pilone,comico,torino,remare,pisolo,volere,tavolo,farina,carota,sedano,banana,timone,pelato,girino,salame,cavolo,marito,condito,vicino,rovente,segnale,tesoro,canale,finire,limone"],
["Trisillabe con gruppi 1","parole","semplici","ditale,mostrare,cattura,vandali,orecchio,pigiama,murati,palazzo,fortuna,postale,bicchiere,dorato,scaldato,silenzio,bolletta,capretta,segnale,tenero,patata,lumaca,signora,camicia,tovaglia,bottiglia"],
["Trisillabe b.f. ortografiche","parole","semplici","risveglio,mugnaio,squillare,cognome,veglione,scacciare,tacchino,richiamo,sequenza,pasquale,sbagliato,matrigna,sceriffo,parcheggio,dovunque,artiglio,ghiacciaio,asciutto,cinquanta,acquario,chitarra"],
["Trisillabe b.f. ortografiche","parole","semplici","inchiostro,succhiare,scivolo,quadretto,sciocchezza,maschietto,strisciare,chimico,agnello,guinzaglio,schizzare,parrocchia,schiacciato"],
["Trisillabe b.f. 1","parole","semplici","rabo,atomo,cedere,carico,suonare,corona,nascita,gustare,terrore,carrello,rapido,massimo,beccare,boccone,faraone,metodo,cicciotto,sudato,saluto,diritto,diffuso,fidare,legato,foglietto,rimedio,nocciola,gabbiano,riunione,azzurro,contorno"],
["Trisillabe b.f. 2","parole","semplici","bibita,cellula,giraffa,cotone,caduta,fanale,ovale,fiducia,soffice,lettore,piccino,orrore,narrare,abile,passeggio,giurare,nobile,carico,carezza,piccione,deluso,letizia,attore,latino,dotare,radura,fisico,paffuto,limite,sedici"],
["Trisillabe b.f. 3","parole","semplici","umore,galassia,vietare,lucciola,orale,tipico,liquido,acciaio,rettile,rigore,rimare,sapore,accorto,aguzzo,cinese,finito,tabella,tifoso,duemila,solido,malato,pennello,basare,rovina,acuto,deciso,rizzare,nocivo,vitello,mutare"],
["Trisillabe b.f. 4","parole","semplici","agire,filato,dannoso,cenere,gettone,cannone,animo,pallino,merito,novità,orario,nemico,bassotto,logico,burrone,ruotare,rilievo,gelido,amato,tossico,carriera,menare,diretto,ridare,pineta,bocciare,mollare,litigio,budino,finora"],
["Trisillabe b.f. 5","parole","semplici","piazzare,ripido,sebbene,civile,piattino,latino,pollice,uranio,appeso,ideale,ciliegio,gocciola,pozione,salice,velluto,fallire,cipolla,zoccolo,tradurre,bollire,vittima,divisa,ticchettio,divino,ferito,parrucca,usato,futuro,pavone,vagone"]
],
//Quadrisillabe
[
["Quadrisillabe b.f. 1","parole","semplici","fabbricare,capitale,ugualmente,personale,offendere,marinaro,casalingo,pubblicità,dinosauro,restituire,calpestare,sconfiggere,navigare,trasferire,profondità,sopracciglio,equipaggio,apprezzare,impegnato,accostare,cartoncino,relazione,invadere,cerimonia,orgoglioso,moschettiere,consigliare,burattino,pianoforte,musicale"],
["Quadrisillabe b.f. 2","parole","semplici","obbedire,concedere,località,arrendersi,pipistrello,isolato,spaventoso,impiegato,cameriere,napoleone,maltrattare,sacrificio,aquilone,educare,giovanotto,popolare,galleggiare,orecchino,coccinella,somigliare,ventiquattro,artistico,raffreddare,navicella,indirizzo,periferia,commettere,anteriore,cimitero,favoloso"],
["Quadrisillabe b.f. 3","parole","semplici","prevedere,mormorare,travestire,poverino,allevare,descrizione,riprovare,apposito,nuvoloso,religione,disordine,immergere,dondolare,meccanico,dichiarare,celebrare,contribuire,illuminato,diminuire,destinare,posteriore,recipiente,vincitore,agricolo,falegname,ricostruire,esistenza,spalancare,comprensione,danneggiare"],
["Quadrisillabe b.f. 4","parole","semplici","sfumatura,cavallino,francobollo,arricchire,militare,informare,incantato,segretario,tramontare,antichità,aranciata,inciampare,sprofondare,sospirare,lampadina,immobile,raggruppare,punizione,panorama,cavalletta,scatenare,giardinetto,solitario,marmellata,intelligenza,umanità,sufficiente,relativo,maturare,dominare"],
["Quadrisillabe b.f. 5","parole","semplici","ingegnere,improvviso,labirinto,dormiglione,comodità,africano,tentativo,nuovamente,sacerdote,investire,confondere,improvviso,sfortunato,infermiere,esitare,infuriare,soffocare,introdurre,consultare,accidenti,convenire,entusiasmo,delusione,annusare,cravatta,affermare,popolare,governare,ospitare,ballerino"],
["Quadrisillabe b.f. 6","parole","semplici","comodino,dipendere,umidità,pomodoro,indumento,ubbidiente,dolcemente,verticale,documento,giornalista,particella,università,incidere,rimandare,partorire,adattare,rallentare,pubblicare,ipotesi,passeggero,venticinque,ripensare,ripulire,proiettare,ricamare,apertura,radunare,rumoroso,soprannome,solletic"],
["Quadrisillabe b.f. 7","parole","semplici","negoziante,decorare,davanzale,solitudine,incastrare,commerciante,giapponese,concorrente,miniatura,applaudire,terremoto,pascolare,porcellino,assegnare,entusiasta,birichino,ricercare,olimpiade,svolazzare,mattinata,prigioniero,pattinaggio,consentire,riprodurre,impastare,elevato,inoltrare,maledetto,rimediare,risultare"],
["Quadrisillabe b.f. 8","parole","semplici","assalire,abitato,incrociare,avvocato,deposito,classifica,ragionare,quotidiano,rosicchiare,limitare,sparecchiare,intrecciare,catechismo,motoscafo,confrontare,assoluto,pasticceria,bastoncino,ricompensa,apprendere,metallico,ferroviario,borbottare,tradizione,conosciuto,commuovere,spolverare,disputare,rinchiudere,contenuto"],
["Quadrisillabe b.f. 9","parole","semplici","rilassare,sussurrare,necessità,scommettere,ingrandire,nocciolina,adottare,arrotolare,indagine,sensibile,passerotto,provvedere,soddisfare,imprimere,variopinto,morsicare,risuonare,attrazione,avvisare,distendere,opinione,parolaccia,malinconia,comunità,favorire,collezione,passatempo,prigioniero,riflessione,antenato"],
["Quadrisillabe b.f. 10","parole","semplici","segnalare,tormentare,serenità,distruzione,appetito,verifica,sgradevole,commerciale,lampadario,vendicare,vergognare,ispirare,lavandino,ufficiale,religioso,quattordici,militare,aggrappare,scavalcare,alfabeto,illustrare,gentilezza,natalizio,precedere,strofinare,concentrare,mandarino,capannone,socchiudere,minaccioso"],
["Quadrisillabe b.f. 11","parole","semplici","avversario,importante,granoturco,affogare,barboncino,braccialetto,divisione,pasticcino,impaziente,bandierina,aggressivo,infelice,girotondo,condannare,artigiano,manifesto,ricambiare,effettuare,benedetto,sorvegliare,femminile,inghiottire,affollato,immondizia,regolare,armatura,predicato,vicinanza,autorità,notevole"],
["Quadrisillabe b.f. 12","parole","semplici","benedetto,specialità,prepotente,padroncino,elencare,papavero,addestrare,vitamina,sospendere,abolire,digerire,astronauta,abbondante,esibire,sbadigliare,ciminiera,normalmente,pellicola,pretendere,funerale,pacifico,componente,grammatica,sconosciuto,giardiniere,affollare,sotterraneo,accudire,chiaramente,penisola"],
["Quadrisillabe b.f. 13","parole","semplici","possibile,condominio,campanile,ripassare,familiare,nascondiglio,microfono,comprensivo,ululare,lontananza,sottoporre,comunale,acquazzone,leggermente,replicare,viceversa,confermare,rassegnare,gentilmente,camminata,saporito,coccolare,essenziale,lavatrice,familiare,longobardo,protezione,discussione,favorevole,faticare"],
["Quadrisillabe b.f. 14","parole","semplici","taglialegna,singolare,differente,necessario,raramente,primitivo,visibile,prenotare,attaccante,rinnovare,sospettare,invitato,municipio,locomotiva,discendere,accusare,ricadere,cassaforte,cattiveria,ritirata,imbarcare,simpatico,rivoltare,confessare,adriatico,liberamente,autentico,antipasto,scappamento,derubare"],
["Quadrisillabe b.f. 15","parole","semplici","prospettiva,macchinario,abbronzare,rincorrere,carnivoro,etichetta,avvenire,pantofola,accogliente,screpolare,innalzare,ombrellone,archeologo,ragioniere,parrucchiere,circolare,applicare,asfaltare,collocare,imboccare,contemplare,riservare,invidiare,manifestare,confidenza,capolavoro,scoraggiare,medesimo,centomila,officina"],
["Quadrisillabe b.f. 16","parole","semplici","approvare,rinchiudere,carburante,disperdere,viaggiatore,precisare,rallegrare,aggirare,ammalato,ingannare,olandese,batuffolo,garantire,traversata,catastrofe,maleducato,maggioranza,sorellastra,accademia,cosiddetto,vulcanico,tenerezza,fischietto,riservato,pubblicitario,deludere,eleggere,pennarello,categoria,programmare"],
["Quadrisillabe b.f. 17","parole","semplici","resistente,ribattere,diecimila,innaffiare,allattare,valutare,avanzato,istruttivo,incendiare,caminetto,edicola,accaduto,espansione,aspirare,ragnatela,minerale,orribile,inventore,crocifisso,abilità,allagare,custodire,banconota,turistico,testolina,sotterraneo,esemplare,eleganza,intervista,racchiudere"],
["Quadrisillabe b.f. 18","parole","semplici","cinquecento,oscurità,spostamento,gradevole,estinguere,acquatico,terraferma,emanare,gentiluomo,telescopio,astronomo,devastare,scintillare,arredare,edizione,camicetta,impigliare,ovviamente,cicatrice,complicato,affilato,annegare,patrimonio,invasione,estremità,spiacevole,oscurare,pisolino,scricchiolare,sopravvivenza"],
["Quadrisillabe b.f. 19","parole","semplici","coltivato,trentacinque,gareggiare,atomico,disabitato,calendario,desolato,germogliare,cannocchiale,espandere,escludere,individuo,nutrimento,vaporetto,curiosare,processione,esplorare,maggiormente,attualmente,apostolo,ottocento,medioevo,iniziale,orientale,catinella,igienico,scatenato,rannicchiare,acquolina,gradinata"],
["Quadrisillabe b.f. 20","parole","semplici","nonostante,rigirare,soleggiato,disboscare,tavoletta,travolgere,negativo,pedalare,galoppare,diligenza,caffettiera,ondeggiare,focolare,azionare,ridicolo,balbettare,sventolare,predicare,cospargere,nevicata,alimento,giapponese,detestare,sbarazzare,attribuire,polverina,scalinata,cittadino,sparpagliare,zampettare"],
["Quadrisillabe b.f. 21","parole","semplici","incarico,cardinale,vegetale,invidioso,lentiggine,ribellare,evidente,colpevole,decorato,insultare,economia,petroliera,impetuoso,tradimento,rilevare,vegetale,capodanno,ceramica,sorreggere,mescolare,sbalordire,incantare,ingessare,permaloso,rattristare,drammatico,tramutare,irrequieto,verniciare,istruttore"],
["Quadrisillabe b.f. 22","parole","semplici","scintillare,politica,pareggiare,rinascere,contentezza,emergere,appannare,travestito,metropoli,vanitoso,addobbare,licenziare,risplendere,avvistare,facilità,illusione,diciassette,materasso,eccezione,testimone,garofano,saccheggiare,maresciallo,laborioso,vittorioso,allarmare,noleggiare,inzuppare,furibondo,accennare"],
["Quadrisillabe b.f. 23","parole","semplici","decollare,intestino,equivoco,monopolio,anticipo,mercatino,pasticcione,indeciso,lucidare,annunziare,iniziale,giardinaggio,elastico,obbligare,imponente,pensionato,gravemente,minestrone,animare,attrezzare,grattacielo,tondeggiante,poveretto,vincitore,commentare,opportuno,culturale,girasole,rigagnolo,acciuffare"],
["Quadrisillabe b.f. 24","parole","semplici","sfruttamento,contributo,innocente,fannullone,analisi,acrobazia,adeguato,spazzolino,fontanella,ingrassare,disprezzare,piramide,esistente,materiale,altrettanto,convocare,esaudire,mozzarella,salutare,indifeso,pitturare,esplodere,canticchiare,parabola,rimbombare,preistorico,ingiustizia,vicinato,romantico,filosofo"],
["Quadrisillabe b.f. 25","parole","semplici","nazionale,inquietare,superiore,camioncino,colpevole,espressivo,estrazione,panettone,australiano,ambientare,arrangiare,gioielleria,anemone,rischiare,riscuotere,prolungare,infinito,roditore,difensore,strabiliante,proclamare,invasore,bastonata,imbroglione,battesimo,bisbigliare,risentire,indagare,constatare,ecologia"],
["Quadrisillabe b.f. 26","parole","semplici","abboccare,rubinetto,alberello,funzionario,pensierino,discoteca,limitato,regionale,riassumere,censimento,sottovoce,britannico,ninna nanna,mascherato,ricopiare,comignolo,camionista,resistenza,raddoppiare,femminuccia,ingrossare,partigiano,polmonare,starnutire,rincasare,scorpacciata,accingere,pallottola,tempestoso,damigella"],
["Quadrisillabe b.f. 27","parole","semplici","cappellino,ufficiale,schiamazzare,circostanza,bruscamente,macinare,copertina,gracidare,conversare,meditare,minigonna,biancospino,dimagrire,dissetare,centesimo,piattaforma,successore,colorato,ambulanza,esattezza,altopiano,esigenza,immediato,installare,quotidiano,salvadanaio,filastrocca,comitiva,assordante,poveretto"],
["Quadrisillabe b.f. 28","parole","semplici","sviluppato,porcellana,singhiozzare,potabile,discepolo,allacciare,sofferenza,giustamente,estinzione,tribunale,identico,socievole,vellutato,portafortuna,fantasioso,ingerire,marachella,pronuncia,salvatore,progettare,seggiolino,sovrapporre,totalmente,pergamena,delinquente,assassino,suscitare,rivivere,modellino,medicare"],
["Quadrisillabe b.f. 29","parole","semplici","fallimento,scarafaggio,formulare,invitante,commissario,raffinato,vertebrato,carrucola,precisione,peperone,arrostire,imbrogliare,rianimare,verdeggiante,stupefare,marittimo,pianeggiante,suonatore,bambolotto,domatore,precauzione,ventinove,emergenza,produttore,cruciverba,millimetro,recintare,ferroviere,scivoloso,arrossire"],
["Quadrisillabe b.f. 30","parole","semplici","somiglianza,accoppiare,cannonata,sterminare,occorrente,cattolico,appassire,imbarazzo,abbellire,pupazzetto,atletico,trascurare,ammiraglio,occidente,incapace,incontrario,contagioso,rincontrare,sonnellino,arruffato,susseguire,fantascienza,trafficare,settecento,infernale,raffreddato,accertare,positivo,rimbalzare,efficace"],
["Quadrisillabe b.f. 31","parole","semplici","giacimento,microscopio,bomboniera,appostare,dinamico,aggettivo,fattorino,cinquemila,segatura,vocabolo,circostante,apparenza,giuramento,rinforzare,ermellino,frequentato,temperino,circolare,stranamente,dentifricio,messaggero,brontolone,lampeggiare,eccellente,compilare,esigere,espellere,sottomesso,accorciare,soffocato"],
["Quadrisillabe b.f. 32","parole","semplici","rispettoso,autografo,saldamente,brizzolato,olimpico,musicista,puntualmente,carpentiere,colossale,confezione,rapinare,costeggiare,uragano,ricorrenza,promozione,riduzione,eschimese,erodere,freddoloso,quadrupede,settecento,protettore,evadere,coinvolgere,caffellatte,dormiveglia,apparente,riordinare,sanguinare,arricciare"],
["Quadrisillabe b.f. 33","parole","semplici","imperiale,prelevare,ammassare,scampagnata,ammonire,avventare,odorare,prodigioso,affittare,benessere,gabinetto,acquisire,indicato,dubitare,ripiegare,traballare,imbiancare,compassione,linguistico,variabile,fortemente,addizione,atterraggio,assetato,preferito,tentazione,cofanetto,dilagare,politico,ispettore"],
["Quadrisillabe b.f. 34","parole","semplici","assistenza,laterale,vivacità,difficile,emigrare,penzolare,scongiurare,spazzolare,convertire,sciroppare,cattedrale,inchiodare,ingiallire,percepire,prelibato,rivendere,fiammeggiante,accordato,personale,usignolo,accampare,soffermare,ambulante,imbottito,accucciarsi,sterminato,tecnologia,riversare,manovrare,allineato"]
]
];
