function Verbo(voce,coniugazione,transitivo,presente,imperfetto,passatoremoto,futurosemplice,condizionale,congiuntivopresente,congiuntivoimperfetto,imperativo,infinito,participiopresente,participiopassato,gerundiopresente,reggenza){
this.voce = voce;
this.coniugazione = coniugazione;
this.transitivo = transitivo;
this.presente = presente;
this.imperfetto = imperfetto;
this.passatoremoto = passatoremoto;
this.futurosemplice = futurosemplice;
this.condizionale = condizionale;
this.congiuntivopresente = congiuntivopresente;
this.congiuntivoimperfetto = congiuntivoimperfetto;
this.imperativo = imperativo;
this.infinito = infinito;
this.participiopresente = participiopresente;
this.participiopassato = participiopassato;
this.gerundiopresente = gerundiopresente;
this.reggenza = reggenza;
}



var persone = ["io","tu","egli","noi","voi","essi"];
var modi = ["indicativo","congiuntivo","condizionale","imperativo","infinito","participio","gerundio"];
var tempiindicativo = ["presente","imperfetto","passato remoto","futuro semplice","passato prossimo","trapassato prossimo","trapassato remoto","futuro anteriore"];
var tempicongiuntivo = ["presente","imperfetto","passato","trapassato"];
var tempicondizionale = ["presente","passato"];
var tempiimperativo = ["presente"];
var tempiinfinito = ["presente","passato"];
var tempiparticipio = ["presente","passato"];
var tempigerundio = ["presente","passato"];

var database = [
new Verbo("essere",
-1,
false,
["sono","sei","è","siamo","siete","sono"],
["ero","eri","era","eravamo","eravate","erano"],
["fui","fosti","fu","fummo","foste","furono"],
["sarò","sarai","sarà","saremo","sarete","saranno"],
["sarei","saresti","sarebbe","saremmo","sareste","sarebbero"],
["sia","sia","sia","siamo","siate","siano"],
["fossi","fossi","fosse","fossimo","foste","fossero"],
["","sii","sia","siamo","siate","siano"],
"essere",
"essente",
["stato","stati"],
"essendo",0),
new Verbo("avere",
-1,
true,
["ho","hai","ha","abbiamo","avete","hanno"],
["avevo","avevi","aveva","avevamo","avevate","avevano"],
["ebbi","avesti","ebbe","avemmo","aveste","ebbero"],
["avrò","avrai","avrà","avremo","avrete","avranno"],
["avrei","avresti","avrebbe","avremmo","avreste","avrebbero"],
["abbia","abbia","abbia","abbiamo","abbiate","abbiano"],
["avessi","avessi","avesse","avessimo","aveste","avessero"],
["","abbi","abbia","abbiamo","abbiate","abbiano"],
"avere",
"avente",
["avuto","avuto"],
"avendo",1),

new Verbo("amare",
1,
true,
["amo","ami","ama","amiamo","amate","amano"],
["amavo","amavi","amava","amavamo","amavate","amavano"],
["amai","amasti","amò","amammo","amaste","amarono"],
["amerò","amerai","amerà","ameremo","amerete","ameranno"],
["amerei","ameresti","amerebbe","ameremmo","amereste","amerebbero"],
["ami","ami","ami","amiamo","amate","amino"],
["ammassi","amassi","amasse","amassimo","amaste","amassero"],
["","ama","ami","amiamo","amate","amino"],
"amare",
"amante",
["amato","amato"],
"amando",1),

new Verbo("andare",
1,
false,
["vado","vai","va","andiamo","andate","vanno"],
["andavo","andavi","andava","andavamo","andavate","andavano"],
["andai","andasti","andò","andammo","andaste","andarono"],
["andrò","andrai","andrà","andremo","andrete","andranno"],
["andrei","andresti","andrebbe","andremmo","andreste","andrebbero"],
["vada","vada","vada","andiamo","andiate","vadano"],
["andassi","andassi","andasse","andassimo","andaste","andassero"],
["","va'/vai","vada","andiamo","andate","vadano"],
"andare",
"andante",
["andato","andati"],
"andando",0),
new Verbo("creare",
1,
true,
["creo","crei","crea","creiamo","create","creano"],
["creavo","creavi","creava","creavamo","creavate","creavano"],
["creai","creasti","creò","creammo","creaste","crearono"],
["creerò","creerai","creerà","creeremo","creerete","creeranno"],
["creerei","creeresti","creerebbe","creeremmo","creereste","creerebbero"],
["crei","crei","crei","creiamo","creiate","creino"],
["creassi","creassi","creasse","creassimo","creaste","creassero"],
["","crea","crei","creiamo","create","creino"],
"creare",
"creante",
["creato","creato"],
"creando",1),
new Verbo("dare",
1,
true,
["do","dai","da","diamo","date","danno"],
["davo","davi","dava","davamo","davate","davano"],
["diedi","desti","diede/dette","demmo","deste","diedero/dettero"],
["darò","darai","darà","daremo","darete","daranno"],
["darei","daresti","darebbe","daremmo","dareste","darebbero"],
["dia","dia","dia","diamo","diate","diano"],
["dessi","dessi","dessi","dessimo","deste","dessero"],
["","da'/dai","dia","diamo","date","diano"],
"dare",
"dante",
["dato","dato"],
"dando",1),
new Verbo("dire",
3,
true,
["dico","dici","dice","diciamo","dite","dicono"],
["dicevo","dicevi","diceva","dicevamo","dicevate","dicevano"],
["dissi","dicesti","disse","dicemmo","diceste","dissero"],
["dirò","dirai","dirà","diremo","direte","diranno"],
["direi","diresti","direbbe","diremmo","direste","direbbero"],
["dica","dica","dica","diciamo","diciate","dicano"],
["dicessi","dicessi","dicessi","dicesse","dicessimo","diceste","dicessero"],
["","di'","dica","diciamo","dite","dicano"],
"dire",
"dicente",
["detto","detto"],
"dicendo",1),
new Verbo("dormire",
3,
false,
["dormo","dormi","dorme","dormiamo","dormite","dormono"],
["dormivo","dormivi","dormiva","dormivamo","dormivate","dormivano"],
["dormii","dormisti","dormì","dormimmo","dormiste","dormirono"],
["dormirò","dormirai","dormirà","dormiremo","dormirete","dormiranno"],
["dormirei","dormiresti","dormirebbe","dormiremmo","dormireste","dormirebbero"],
["dorma","dorma","dorma","dormiamo","dormiate","dormano"],
["dormissi","dormissi","dormisse","dormissimo","dormiste","dormissero"],
["","dormi","dorma","dormiamo","dormite","dormano"],
"dormire",
"dormente/iente",
["dormito","dormito"],
"dormendo",1),
new Verbo("fare",
1,
true,
["faccio","fai","fa","facciamo","fate","fanno"],
["facevo","facevi","faceva","facevamo","facevate","facevano"],
["feci","facesti","fece","facemmo","faceste","fecero"],
["farò","farai","farà","faremo","farete","faranno"],
["farei","faresti","farebbe","faremmo","fareste","farebbero"],
["faccia","faccia","faccia","facciamo","facciate","facciano"],
["facessi","facessi","facesse","facessimo","faceste","facessero"],
["","fa'/fai","faccia","facciamo","fate","facciano"],
"fare",
"facente",
["fatto","fatto"],
"facendo",1),
new Verbo("giocare",
1,
false,
["gioco","giochi","gioca","giochiamo","giocate","giocano"],
["giocavo","giocavi","giocava","giocavamo","giocavate","giocavano"],
["giocai","giocasti","giocò","giocammo","giocaste","giocarono"],
["giocherò","giocherai","giocherà","giocheremo","giocherete","giocheranno"],
["giocherei","giocheresti","giocherebbe","giocheremmo","giochereste","giocherebbero"],
["giochi","giochi","giochi","giochiamo","giochiate","giochino"],
["giocassi","giocassi","giocasse","giocassimo","giocaste","giocassero"],
["","gioca","giochi","giochiamo","giocate","giochino"],
"giocare",
"giocante",
["giocato","giocato"],
"giocando",1),
new Verbo("leggere",
2,
true,
["leggo","leggi","legge","leggiamo","leggete","leggono"],
["leggevo","leggevi","leggeva","leggevamo","leggevate","leggevano"],
["lessi","leggesti","lesse","leggemmo","leggeste","lessero"],
["leggerò","leggerai","leggerà","leggeremo","leggerete","leggeranno"],
["leggerei","leggeresti","leggerebbe","leggeremmo","leggereste","leggerebbero"],
["legga","legga","legga","leggiamo","leggiate","leggano"],
["leggessi","leggessi","leggesse","leggessimo","leggeste","leggessero"],
["","leggi","legga","leggiamo","leggete","leggano"],
"leggere",
"leggente",
["letto","letto"],
"leggendo",1),
new Verbo("mangiare",
1,
true,
["mangio","mangi","mangia","mangiamo","mangiate","mangiano"],
["mangiavo","mangiavi","mangiava","mangiavamo","mangiavate","mangiavano"],
["mangiai","mangiasti","mangiò","mangiammo","mangiaste","mangiarono"],
["mangerò","mangerai","mangerà","mangeremo","mangerete","mangeranno"],
["mangerei","mangeresti","mangerebbe","mangeremmo","mangereste","mangerebbero"],
["mangi","mangi","mangi","mangiamo","mangiate","mangino"],
["mangiassi","mangiassi","mangiasse","mangiassimo","mangiaste","mangiassero"],
["","mangia","mangi","mangiamo","mangiate","mangino"],
"mangiare",
"mangiante",
["mangiato","mangiato"],
"mangiando",1),
new Verbo("parlare",
1,
false,
["parlo","parli","parla","parliamo","parlate","parlano"],
["parlavo","parlavi","parlava","parlavamo","parlavate","parlavano"],
["parlai","piacesti","piacque","piacemmo","piaceste","piacquero"],
["parlerò","parlerai","parlerà","parleremo","parlerete","parleranno"],
["parlerei","parleresti","parlerebbe","parleremmo","parlereste","parlerebbero"],
["parli","parli","parli","parliamo","parliate","parlino"],
["parlassi","parlassi","parlasse","parlassimo","parlaste","parlassero"],
["","parla","parli","parliamo","parlate","parlino"],
"parlare",
"parlante",
["parlato","parlato"],
"parlando",1),
new Verbo("piacere",
2,
false,
["piaccio","paci","piace","piacciamo","piacete","piacciono"],
["piacevo","piacevi","piaceva","piacevamo","piacevate","piacevano"],
["piacqui","piacesti","piacque","piacemmo","piaceste","piacquero"],
["piacerò","piacerai","piacerà","piaceremo","piacerete","piaceranno"],
["piacerei","piaceresti","piacerebbe","piaceremmo","piacereste","piacerebbero"],
["piaccia","piaccia","piaccia","piacciamo","piacciate","piacciano"],
["piacessi","piacessi","piacesse","piacessimo","piaceste","piacessero"],
["","piaci","piaccia","piacciamo","piacete","piacciano"],
"piacere",
"piacente",
["piaciuto","piaciuti"],
"piacendo",0),
new Verbo("potere",
2,
false,
["posso","puoi","può","possiamo","potete","possono"],
["potevo","potevi","poteva","potevamo","potevate","potevano"],
["potetti/potei","potesti","potette/poté","potemmo","poteste","potettero/poterono"],
["potrò","potrai","potrà","potremo","potrete","potranno"],
["potrei","potresti","potrebbe","potremmo","potreste","potrebbero"],
["possa","possa","possa","possiamo","possiate","possano"],
["potessi","potessi","potesse","potessimo","poteste","potessero"],
["","puoi","possa","possiamo","potete","possano"],
"potere",
"potente",
["potuto","potuto"],
"potendo",1),
new Verbo("portare",
1,
true,
["porto","porti","porta","portiamo","portate","portano"],
["portavo","portavi","portava","portavamo","portavate","portavano"],
["portai","portasti","portò","portammo","portaste","portarono"],
["porterò","porterai","porterà","porteremo","porterete","porteranno"],
["porterei","porteresti","porterebbe","porteremmo","portereste","porterebbero"],
["porti","porti","porti","portiamo","portiate","portino"],
["portassi","portassi","portasse","portassimo","portaste","portassero"],
["","porta","porti","portiamo","portate","portino"],
"portare",
"portante",
["portato","portato"],
"portando",1),
new Verbo("sapere",
2,
true,
["so","sai","sa","sappiamo","sapete","sanno"],
["sapevo","sapevi","sapeva","sapevamo","sapevate","sapevano"],
["seppi","sapesti","seppe","sapemmo","sapeste","seppero"],
["saprò","saprai","saprà","sapremo","saprete","sapranno"],
["saprei","sapresti","saprebbe","sapremmo","sapreste","saprebbero"],
["sappia","sappia","sappia","sappiamo","sappiate","sappiano"],
["sapessi","sapessi","sapessi","sapessimo","sapeste","sapessero"],
["","sappi","sappia","sappiamo","sappiate","sappiano"],
"sapere",
"sapiente",
["saputo","saputo"],
"sapendo",1),
new Verbo("sentire",
3,
true,
["sento","senti","sente","sentiamo","sentite","sentono"],
["sentivo","sentivi","sentiva","sentivamo","sentivate","sentivano"],
["sentii","sentisti","sentì","sentimmo","sentiste","sentirono"],
["sentirò","sentirai","sentirà","sentiremo","sentirete","sentiranno"],
["sentirei","sentiresti","sentirebbe","sentiremmo","sentireste","sentirebbero"],
["senta","senta","senta","sentiamo","sentiate","sentano"],
["sentissi","sentissi","sentisse","sentissimo","sentiste","sentissero"],
["","senti","senta","sentiamo","sentite","sentano"],
"sentire",
"senziente",
["sentito","sentito"],
"sentendo",1),
new Verbo("stare",
1,
false,
["sto","stai","sta","siamo","state","stanno"],
["stavo","stavi","stava","stavamo","stavate","stavano"],
["stetti","stesti","stette","stemmo","steste","stettero"],
["starò","starai","starà","staremo","starete","staranno"],
["starei","staresti","starebbe","staremmo","stareste","starebbero"],
["stia","stia","stia","stiamo","stiate","stiano"],
["stessi","stessi","stesse","stessimo","steste","stessero"],
["","sta/stai","stia","stiamo","state","stiano"],
"stare",
"stante",
["stato","stati"],
"stando",0),
new Verbo("tornare",
1,
false,
["torno","torni","torna","torniamo","tornate","tornano"],
["tornavo","tornavi","tornava","tornavamo","tornavate","tornavano"],
["tornai","tornasti","tornò","tornammo","tornaste","tornarono"],
["tornerò","tornerai","tornerà","torneremo","tornerete","torneranno"],
["tornerei","torneresti","tornerebbe","torneremmo","tornereste","tornerebbero"],
["torni","torni","torni","torniamo","torniate","tornino"],
["tornassi","tornassi","tornasse","tornassimo","tornaste","tornassero"],
["","torna","torni","torniamo","tornate","tornino"],
"tornare",
"tornante",
["tornato","tornati"],
"tornando",0),
new Verbo("vedere",
2,
true,
["vedo","vedi","vede","vediamo","vedete","vedono"],
["vedevo","vedevi","vedeva","vedevamo","vedevate","vedevano"],
["vidi","vedesti","vide","vedemmo","vedeste","videro"],
["vedrò","vedrai","vedrà","vedremo","vedrete","vedranno"],
["vedrei","vedresti","vedrebbe","vedremmo","vedreste","vedrebbero"],
["veda","veda","veda","vediamo","vediate","vedano"],
["vedessi","vedessi","vedesse","vedessimo","vedeste","vedessero"],
["","vedi","veda","vediamo","vedete","vedano"],
"vedere",
"vedente",
["visto","visto"],
"vedendo",1),
new Verbo("volere",
2,
true,
["voglio","vuoi","vuole","vogliamo","volete","vogliono"],
["volevo","volevi","voleva","volevamo","volevate","volevano"],
["volli","volesti","volle","volemmo","voleste","vollero"],
["vorrò","vorrai","vorrà","vorremo","vorrete","vorranno"],
["vorrei","vorresti","vorrebbe","vorremmo","vorreste","vorrebbero"],
["voglia","voglia","voglia","vogliamo","vogliate","vogliano"],
["volessi","volessi","volesse","volessimo","voleste","volessero"],
["","vuoi","voglia","vogliamo","volete","vogliano"],
"volere",
"volente",
["voluto","voluto"],
"volendo",1),
]

